/**
 * 
 */
package org.getalp.dbnary.pol;

import java.util.HashMap;

import org.getalp.dbnary.LangTools;


public class PolishLangToCode extends LangTools {
	static HashMap<String,String> h = new HashMap<String,String>();
	static {
		h.put("język arczyński", "aqc");
		h.put("język iwam", "iwm");
		h.put("marokańska odmiana języka arabskiego", "ary");
		h.put("dialekt egipski języka arabskiego", "arz");
		h.put("arawak", "arw");
		h.put("język arapaho", "arp");
		h.put("arapaho", "arp");
		h.put("araukański", "arn");
		h.put("język mapudungun", "arn");
		h.put("aragoński", "arg");
		h.put("język aragoński", "arg");
		h.put("aramejski", "arc");
		h.put("arabski", "ara");
		h.put("język arabski", "ara");
		h.put("zazaki", "zza");
		h.put("język ingryjski", "izh");
		h.put("brak treści o charakterze lingwistycznym", "zxx");
		h.put("język awarski", "ava");
		h.put("awarski", "ava");
		h.put("język ǂkx'au'ǁ'ein", "aue");
		h.put("awadhi", "awa");
		h.put("awadhi", "awa");
		h.put("język awestyjski", "ave");
		h.put("awestyjski", "ave");
		h.put("język au", "avt");
		h.put("asturyjski", "ast");
		h.put("język asturyjski", "ast");
		h.put("asu", "asa");
		h.put("język pare", "asa");
		h.put("język assiniboine", "asb");
		h.put("język aszkun", "ask");
		h.put("asamski", "asm");
		h.put("język asamski", "asm");
		h.put("język atsina", "ats");
		h.put("język keczua", "que");
		h.put("keczua", "que");
		h.put("język kicze", "quc");
		h.put("język jamajski", "jam");
		h.put("język ajmara", "aym");
		h.put("ajmara", "aym");
		h.put("język azerski", "aze");
		h.put("azerski", "aze");
		h.put("jawajski", "jav");
		h.put("język krymczacki", "jct");
		h.put("język kaszkajski", "qxq");
		h.put("lojban", "jbo");
		h.put("lojban", "jbo");
		h.put("język judeo-berberyjski", "jbe");
		h.put("quenya", "qya");
		h.put("język judeo-gruziński", "jge");
		h.put("język abau", "aau");
		h.put("język ankave", "aak");
		h.put("afar", "aar");
		h.put("język afar", "aar");
		h.put("język zimakani", "zik");
		h.put("język zia", "zia");
		h.put("język koro", "jkr");
		h.put("język kreolski reunionu", "rcf");
		h.put("język chiński", "zho");
		h.put("rarotonga", "rar");
		h.put("język radżastani", "raj");
		h.put("radźasthani", "raj");
		h.put("język zhuang", "zha");
		h.put("czuang", "zha");
		h.put("rapanui", "rap");
		h.put("język rapanui", "rap");
		h.put("język arabski rejonu zatoki perskiej", "afb");
		h.put("machame", "jmc");
		h.put("język adygejski", "ady");
		h.put("adygejski", "ady");
		h.put("język amdo", "adx");
		h.put("adangme", "ada");
		h.put("aceh", "ace");
		h.put("język aceh", "ace");
		h.put("język kott", "zko");
		h.put("dialekty mezopotamskie języka arabskiego", "acm");
		h.put("język akar-bale", "acl");
		h.put("język kitański", "zkt");
		h.put("aczoli", "ach");
		h.put("język abazyński", "abq");
		h.put("judeoperski", "jpr");
		h.put("japoński", "jpn");
		h.put("język japoński", "jpn");
		h.put("język abui", "abz");
		h.put("język aka-bea", "abj");
		h.put("język abchaski", "abk");
		h.put("abchaski", "abk");
		h.put("język tarifit", "rif");
		h.put("ajnu", "ain");
		h.put("język ajnuski", "ain");
		h.put("język airoran", "air");
		h.put("język zarfatit", "zrp");
		h.put("język nyaturu", "rim");
		h.put("język akha", "ahk");
		h.put("judeoarabski", "jrb");
		h.put("język judeo-arabski", "jrb");
		h.put("język ahom", "aho");
		h.put("język asyryjski", "aii");
		h.put("malajski", "zsm");
		h.put("język rohingya", "rhg");
		h.put("aghem", "agq");
		h.put("język argobba", "agj");
		h.put("język agulski", "agx");
		h.put("afrikaans", "afr");
		h.put("język afrikaans", "afr");
		h.put("afrihili", "afh");
		h.put("język staroangielski", "ang");
		h.put("staroangielski", "ang");
		h.put("język andyjski", "ani");
		h.put("caló", "rmq");
		h.put("język domari", "rmt");
		h.put("język anal", "anm");
		h.put("angika", "anp");
		h.put("język jarawa", "anq");
		h.put("dialekt toskijski języka albańskiego", "als");
		h.put("południowoałtajski", "alt");
		h.put("język algonkiński", "alq");
		h.put("język alutorski", "alr");
		h.put("język alur", "alz");
		h.put("amharski", "amh");
		h.put("język amanab", "amn");
		h.put("język alamblak", "amp");
		h.put("rombo", "rof");
		h.put("język achwaski", "akv");
		h.put("retoromański", "roh");
		h.put("język romansz", "roh");
		h.put("język romski", "rom");
		h.put("cygański", "rom");
		h.put("język rumuński", "ron");
		h.put("rumuński", "ron");
		h.put("aleucki", "ale");
		h.put("język aleucki", "ale");
		h.put("język amaimon", "ali");
		h.put("język ronga", "rng");
		h.put("język akan", "aka");
		h.put("akan", "aka");
		h.put("zuni", "zun");
		h.put("język zulu", "zul");
		h.put("zulu", "zul");
		h.put("język bo", "akm");
		h.put("język akadyjski", "akk");
		h.put("akadyjski", "akk");
		h.put("język bodo", "brx");
		h.put("bodo", "brx");
		h.put("język pali", "pli");
		h.put("palijski", "pli");
		h.put("polari", "pld");
		h.put("język palajski", "plq");
		h.put("język bradź", "bra");
		h.put("bradź", "bra");
		h.put("język bretoński", "bre");
		h.put("bretoński", "bre");
		h.put("język brahui", "brh");
		h.put("akose", "bss");
		h.put("język jukagirski południowy", "yux");
		h.put("język szera-jögurski", "yuy");
		h.put("język zachodniopendżabski", "pnb");
		h.put("jugh", "yuu");
		h.put("język pol", "pmm");
		h.put("język maya", "yua");
		h.put("język baszkardi", "bsg");
		h.put("język tuamotu", "pmt");
		h.put("język piemoncki", "pms");
		h.put("język buruszaski", "bsk");
		h.put("standardowy język kantoński", "yue");
		h.put("kantoński", "yue");
		h.put("bugiński", "bug");
		h.put("język bugijski", "bug");
		h.put("buriacki", "bua");
		h.put("język buriacki", "bua");
		h.put("bulu", "bum");
		h.put("język bulu", "bum");
		h.put("język bułgarski", "bul");
		h.put("bułgarski", "bul");
		h.put("kanembu", "kbl");
		h.put("język bubi", "bvb");
		h.put("kabardyjski", "kbd");
		h.put("język kabardyjski", "kbd");
		h.put("staroprowansalski", "pro");
		h.put("język wasi-weri", "prn");
		h.put("kawi", "kaw");
		h.put("język kazachski", "kaz");
		h.put("kazachski", "kaz");
		h.put("język pruski", "prg");
		h.put("język kapuczyński", "kap");
		h.put("kannada", "kan");
		h.put("język kannada", "kan");
		h.put("kanuri", "kau");
		h.put("język kanuri", "kau");
		h.put("język gruziński", "kat");
		h.put("gruziński", "kat");
		h.put("kaszmirski", "kas");
		h.put("język kaszmirski", "kas");
		h.put("grenlandzki", "kal");
		h.put("język grenlandzki", "kal");
		h.put("kamba", "kam");
		h.put("jju", "kaj");
		h.put("kaczin", "kac");
		h.put("język karakałpacki", "kaa");
		h.put("karakałpacki", "kaa");
		h.put("kabylski", "kab");
		h.put("język kabylski", "kab");
		h.put("język pontyjski", "pnt");
		h.put("medumba", "byv");
		h.put("język kreolski gwinei-bissau", "pov");
		h.put("język połabski", "pox");
		h.put("blin", "byn");
		h.put("język polski", "pol");
		h.put("polski", "pol");
		h.put("portugalski", "por");
		h.put("ponpejski", "pon");
		h.put("język kreolski belize", "bzj");
		h.put("koro", "kfo");
		h.put("brithenig", "bzt");
		h.put("język kaććhi", "kfr");
		h.put("język kumauni", "kfy");
		h.put("język punu", "puu");
		h.put("pasztuński", "pus");
		h.put("paszto", "pus");
		h.put("język kusunda", "kgg");
		h.put("język kekczi", "kek");
		h.put("język ketyjski", "ket");
		h.put("język kodava", "kfa");
		h.put("język kota", "kfe");
		h.put("makonde", "kde");
		h.put("język karaimski", "kdr");
		h.put("mowa znaków", "psd");
		h.put("kreolski wysp zielonego przylądka", "kea");
		h.put("język kreolski wysp zielonego przylądka", "kea");
		h.put("bliss", "zbl");
		h.put("bliss", "zbl");
		h.put("język kélé", "keb");
		h.put("polski język migowy", "pso");
		h.put("tyap", "kcg");
		h.put("język chantyjski", "kca");
		h.put("język kalanga", "kck");
		h.put("język zaghawa", "zag");
		h.put("język zapotecki", "zap");
		h.put("zapotecki", "zap");
		h.put("język kaka", "kkj");
		h.put("kako", "kkj");
		h.put("język tai khun", "kkh");
		h.put("język ch'orti'", "caa");
		h.put("język garifuna", "cab");
		h.put("język chuj", "cac");
		h.put("kaddo", "cad");
		h.put("język tofa", "kim");
		h.put("kinya-ruanda", "kin");
		h.put("język ruanda-rundi", "kin");
		h.put("język kirgiski", "kir");
		h.put("kirgiski", "kir");
		h.put("język khmu", "kjg");
		h.put("język chinalugijski", "kjj");
		h.put("karibi", "car");
		h.put("język kataloński", "cat");
		h.put("kataloński", "cat");
		h.put("język karoliński", "cal");
		h.put("język kaqchikel", "cak");
		h.put("język chwarszyjski", "khv");
		h.put("język khowar", "khw");
		h.put("język kapori", "khp");
		h.put("koyra chini", "khq");
		h.put("khmerski", "khm");
		h.put("cayuga", "cay");
		h.put("chotański", "kho");
		h.put("język kikuju", "kik");
		h.put("kikuju", "kik");
		h.put("język chavacano", "cbk");
		h.put("dialekt zelandzki", "zea");
		h.put("atsam", "cch");
		h.put("język kham", "khg");
		h.put("język tai lue", "khb");
		h.put("język czakma", "ccp");
		h.put("język khasi", "kha");
		h.put("khasi", "kha");
		h.put("zenaga", "zen");
		h.put("konkani", "knn");
		h.put("język bacbijski", "bbl");
		h.put("ghomala", "bbj");
		h.put("język yidgański", "ydg");
		h.put("język beludżi", "bal");
		h.put("beludżi", "bal");
		h.put("komi", "kom");
		h.put("język komi", "kom");
		h.put("bambara", "bam");
		h.put("język bambara", "bam");
		h.put("kongo", "kon");
		h.put("język kongo", "kon");
		h.put("język balijski", "ban");
		h.put("balijski", "ban");
		h.put("język komi-permiacki", "koi");
		h.put("język konkani", "kok");
		h.put("baszkirski", "bak");
		h.put("język baszkirski", "bak");
		h.put("język kol", "kol");
		h.put("bamun", "bax");
		h.put("język kota", "koq");
		h.put("język koreański", "kor");
		h.put("koreański", "kor");
		h.put("kosrae", "kos");
		h.put("basa", "bas");
		h.put("język basaa", "bas");
		h.put("język yimas", "yee");
		h.put("język jewanik", "yej");
		h.put("kalenjin", "kln");
		h.put("język guugu yimithirr", "kky");
		h.put("język buduchyjski", "bdk");
		h.put("język kurmandżi", "kmr");
		h.put("kimbundu", "kmb");
		h.put("język mbundu", "kmb");
		h.put("język kryzyjski", "kry");
		h.put("kurukh", "kru");
		h.put("język kurukh", "kru");
		h.put("język bagheli", "bfy");
		h.put("język badaga", "bfq");
		h.put("język kerecki", "krk");
		h.put("język bunak", "bfn");
		h.put("karelski", "krl");
		h.put("język karelski", "krl");
		h.put("język kinaraya", "krj");
		h.put("język karaczajsko-bałkarski", "krc");
		h.put("karaczajsko-bałkarski", "krc");
		h.put("bafut", "bfd");
		h.put("bena", "bez");
		h.put("język bena", "bez");
		h.put("język białoruski", "bel");
		h.put("białoruski", "bel");
		h.put("język bemba", "bem");
		h.put("bemba", "bem");
		h.put("język bengalski", "ben");
		h.put("bengalski", "ben");
		h.put("język bedża", "bej");
		h.put("bedża", "bej");
		h.put("jidysz", "yid");
		h.put("jidysz", "yid");
		h.put("bafia", "ksf");
		h.put("język bafia", "ksf");
		h.put("gwara kolońska", "ksh");
		h.put("język rypuaryjski", "ksh");
		h.put("sambala", "ksb");
		h.put("język sambala", "ksb");
		h.put("język kobon", "kpw");
		h.put("język jukagirski północny", "ykg");
		h.put("język karatajski", "kpt");
		h.put("język tehit", "kps");
		h.put("język koriacki", "kpy");
		h.put("kpelle", "kpe");
		h.put("język kpelle", "kpe");
		h.put("język bhodźpuri", "bho");
		h.put("bhodźpuri", "bho");
		h.put("karaja", "kpj");
		h.put("język bucharski", "bhh");
		h.put("język yele", "yle");
		h.put("język kaonde", "kqn");
		h.put("język bangandu", "bgf");
		h.put("język banjar", "bjn");
		h.put("język yameo", "yme");
		h.put("bini", "bin");
		h.put("bikol", "bik");
		h.put("język kwanga", "kwj");
		h.put("język bislama", "bis");
		h.put("bislama", "bis");
		h.put("język jul'hoan", "ktz");
		h.put("język yola", "yol");
		h.put("język kwanyama", "kua");
		h.put("kwanyama", "kua");
		h.put("kom", "bkm");
		h.put("język joruba", "yor");
		h.put("joruba", "yor");
		h.put("język kunama", "kun");
		h.put("kumycki", "kum");
		h.put("kutenai", "kut");
		h.put("język kurdyjski", "kur");
		h.put("kurdyjski", "kur");
		h.put("siksika", "bla");
		h.put("język siksika", "bla");
		h.put("język bilua", "blb");
		h.put("język nuxálk", "blc");
		h.put("język bagulalski", "kva");
		h.put("język bośniacki", "bos");
		h.put("bośniacki", "bos");
		h.put("tybetański", "bod");
		h.put("język tybetański", "bod");
		h.put("język bangi", "bni");
		h.put("język bisznuprija-manipuri", "bpy");
		h.put("język bachtiarski", "bqi");
		h.put("język kapori", "bpp");
		h.put("język kazukuru", "kzk");
		h.put("język botlichyjski", "bph");
		h.put("język ladakhi", "lbj");
		h.put("język lakijski", "lbe");
		h.put("walijski", "cym");
		h.put("język walijski", "cym");
		h.put("język lele", "lel");
		h.put("język lepcza", "lep");
		h.put("język lezgiński", "lez");
		h.put("lezgijski", "lez");
		h.put("język onondaga", "ono");
		h.put("język wenetyjski", "xve");
		h.put("język knaan", "czk");
		h.put("język wandalski", "xvn");
		h.put("język minzhong", "czo");
		h.put("láadan", "ldn");
		h.put("język o'odham", "ood");
		h.put("język umbryjski", "xum");
		h.put("język urartyjski", "xur");
		h.put("ladino", "lad");
		h.put("ladyński", "lad");
		h.put("język scytyjski", "xsc");
		h.put("lahnda", "lah");
		h.put("langi", "lag");
		h.put("język langi", "lag");
		h.put("język sempan", "xse");
		h.put("język sydetyjski", "xsd");
		h.put("język oirata", "oia");
		h.put("łaciński", "lat");
		h.put("łacina", "lat");
		h.put("łotewski", "lav");
		h.put("język jaćwiński", "xsv");
		h.put("lamba", "lam");
		h.put("język szerpa", "xsr");
		h.put("laotański", "lao");
		h.put("język laotański", "lao");
		h.put("klasyczny język japoński", "ojp");
		h.put("język odżibwe", "oji");
		h.put("odżibwa", "oji");
		h.put("język retycki", "xrr");
		h.put("slave", "den");
		h.put("język ladyński", "lld");
		h.put("delaware", "del");
		h.put("język delaware", "del");
		h.put("niemiecki", "deu");
		h.put("język starosaksoński", "osx");
		h.put("język lakota", "lkt");
		h.put("osmańsko-turecki", "ota");
		h.put("język osmańsko-turecki", "ota");
		h.put("język !o!kung", "oun");
		h.put("yangben", "yav");
		h.put("yemba", "ybb");
		h.put("język longobardzki", "lng");
		h.put("język jagnobijski", "yai");
		h.put("język jazgulamski", "yah");
		h.put("japski", "yap");
		h.put("yao", "yao");
		h.put("dakhini", "dcc");
		h.put("język lombardzki", "lmo");
		h.put("lambadi", "lmn");
		h.put("język fataluku", "ddg");
		h.put("dargwijski", "dar");
		h.put("duński", "dan");
		h.put("język duński", "dan");
		h.put("język oksapmin", "opm");
		h.put("język dahalo", "dal");
		h.put("dakota", "dak");
		h.put("oorlans", "oor");
		h.put("język dyirbal", "dbl");
		h.put("lingua franca nova", "lfn");
		h.put("taita", "dav");
		h.put("język orokolo", "oro");
		h.put("język oromo", "orm");
		h.put("oromski", "orm");
		h.put("język orija", "ori");
		h.put("orija", "ori");
		h.put("język liwski", "liv");
		h.put("litewski", "lit");
		h.put("język litewski", "lit");
		h.put("język lisu", "lis");
		h.put("limburgijski", "lim");
		h.put("język limburski", "lim");
		h.put("język st’át’imcets", "lil");
		h.put("dialekt monegaski", "lij");
		h.put("język libido", "liq");
		h.put("lingala", "lin");
		h.put("język lingala", "lin");
		h.put("osetyjski", "oss");
		h.put("język osetyjski", "oss");
		h.put("język limbu", "lif");
		h.put("osage", "osa");
		h.put("język oskijski", "osc");
		h.put("język zemgalski", "xzm");
		h.put("język szangszung", "xzh");
		h.put("język staroruski", "orv");
		h.put("język czukocki", "ckt");
		h.put("język galindyjski", "xgl");
		h.put("język hunów", "xhc");
		h.put("język czamalalski", "cji");
		h.put("język średniochiński", "ltc");
		h.put("język łatgalski", "ltg");
		h.put("język xhosa", "xho");
		h.put("khosa", "xho");
		h.put("język jin", "cjy");
		h.put("język hurycki", "xhu");
		h.put("język sorani", "ckb");
		h.put("sorani kurdyjski", "ckb");
		h.put("luksemburski", "ltz");
		h.put("język luksemburski", "ltz");
		h.put("język iberyjski", "xib");
		h.put("luba", "lua");
		h.put("luba-lulua", "lua");
		h.put("język eblaicki", "xeb");
		h.put("luiseno", "lui");
		h.put("język laua", "luf");
		h.put("język luganda", "lug");
		h.put("ganda", "lug");
		h.put("luba-katanga", "lub");
		h.put("język lucumi", "luq");
		h.put("lunda", "lun");
		h.put("język lunda", "lun");
		h.put("język luo", "luo");
		h.put("luo", "luo");
		h.put("luyia", "luy");
		h.put("język luhya", "luy");
		h.put("język luszucid", "lut");
		h.put("język mizo", "lus");
		h.put("lushai", "lus");
		h.put("język pangasinan", "pag");
		h.put("pangasino", "pag");
		h.put("pendżabski", "pan");
		h.put("język pendżabski", "pan");
		h.put("język pampango", "pam");
		h.put("pampango", "pam");
		h.put("język pahlawi", "pal");
		h.put("pahlavi", "pal");
		h.put("język faliskijski", "xfa");
		h.put("język czagatajski", "chg");
		h.put("czagatajski", "chg");
		h.put("język lavukaleve", "lvk");
		h.put("język czeczeński", "che");
		h.put("czeczeński", "che");
		h.put("język czoktaw", "cho");
		h.put("choctaw", "cho");
		h.put("chipewyan", "chp");
		h.put("język czirokeski", "chr");
		h.put("czirokeski", "chr");
		h.put("język łotewski", "lvs");
		h.put("truk", "chk");
		h.put("maryjski", "chm");
		h.put("język maryjski", "chm");
		h.put("żargon chinook", "chn");
		h.put("język czejenów", "chy");
		h.put("język czejeński", "chy");
		h.put("czuwaski", "chv");
		h.put("język czuwaski", "chv");
		h.put("język staro-cerkiewno-słowiański", "chu");
		h.put("staro-cerkiewno-słowiański", "chu");
		h.put("język cia-cia", "cia");
		h.put("język galatyjski", "xga");
		h.put("język celtyberyjski", "xce");
		h.put("język kamunicki", "xcc");
		h.put("język kumbryjski", "xcb");
		h.put("chiga", "cgg");
		h.put("język chiga", "cgg");
		h.put("chamorro", "cha");
		h.put("język czamorro", "cha");
		h.put("język kuroński", "xcu");
		h.put("czibcza", "chb");
		h.put("język karyjski", "xcr");
		h.put("język chorezmijski", "xco");
		h.put("język mongo", "lol");
		h.put("mongo", "lol");
		h.put("grabar", "xcl");
		h.put("lozi", "loz");
		h.put("język lozi", "loz");
		h.put("język dacki", "xdc");
		h.put("język cebuański", "ceb");
		h.put("cebuano", "ceb");
		h.put("język czeski", "ces");
		h.put("czeski", "ces");
		h.put("język albański", "xag");
		h.put("język kałmucki", "xal");
		h.put("kałmucki", "xal");
		h.put("język baktryjski", "xbc");
		h.put("język laragiya", "lrg");
		h.put("język mindong", "cdo");
		h.put("język protobułgarski", "xbo");
		h.put("język piktyjski", "xpi");
		h.put("język frygijski", "xpg");
		h.put("język partyjski", "xpr");
		h.put("język pizydyjski", "xps");
		h.put("język chatgaya", "ctg");
		h.put("gwary palatynackie", "pfl");
		h.put("język punicki", "xpu");
		h.put("kaszubski", "csb");
		h.put("język kaszubski", "csb");
		h.put("krymski turecki", "crh");
		h.put("język krymskotatarski", "crh");
		h.put("język miszif", "crg");
		h.put("język neosalomoński", "pis");
		h.put("język kreolski wyspy św. tomasza i książęcej", "cri");
		h.put("język kreolski seszelski", "crs");
		h.put("język pitkarnyjski", "pih");
		h.put("język kri", "cre");
		h.put("kri", "cre");
		h.put("fenicki", "phn");
		h.put("język fenicki", "phn");
		h.put("soga", "xog");
		h.put("język puxian", "cpx");
		h.put("język liburnijski", "xli");
		h.put("język lidyjski", "xld");
		h.put("język lemnijski", "xle");
		h.put("język liguryjski", "xlg");
		h.put("pidżyn nigeryjski", "pcm");
		h.put("język kamula", "xla");
		h.put("język licyjski", "xlc");
		h.put("język buyei", "pcc");
		h.put("pidżyn chińsko-angielski", "cpi");
		h.put("język pikardyjski", "pcd");
		h.put("język pyu", "pby");
		h.put("język kornijski", "cor");
		h.put("kornijski", "cor");
		h.put("korsykański", "cos");
		h.put("język macedoński", "xmk");
		h.put("koptyjski", "cop");
		h.put("język koptyjski", "cop");
		h.put("język megrelski", "xmf");
		h.put("język chicomuceltec", "cob");
		h.put("palau", "pau");
		h.put("język palau", "pau");
		h.put("język lepontyjski", "xlp");
		h.put("język parija", "paq");
		h.put("papiamento", "pap");
		h.put("język papiamento", "pap");
		h.put("język staroperski", "peo");
		h.put("staroperski", "peo");
		h.put("klasyczny język chiński", "lzh");
		h.put("język mesapijski", "cms");
		h.put("języki ilirskie", "xil");
		// h.put("chiński", "cmn");
		h.put("języki mandaryńskie", "cmn");
		h.put("język mongolski klasyczny", "cmg");
		h.put("plautdietsch", "pdt");
		h.put("język lazyjski", "lzz");
		h.put("język niemiecki w pensylwanii", "pdc");
		h.put("język klallam", "clm");
		h.put("język mewati", "wtm");
		h.put("język ao", "njo");
		h.put("język berta", "wti");
		h.put("język dumpu", "wtf");
		h.put("język mogolski", "mhj");
		h.put("język mikmak", "mic");
		h.put("micmac", "mic");
		h.put("język nkutu", "nkw");
		h.put("makhuwa meetto", "mgh");
		h.put("niderlandzki", "nld");
		h.put("język niderlandzki", "nld");
		h.put("język matumbi", "mgw");
		h.put("język kreolski mauritiusa", "mfe");
		h.put("kreolski mauritiusa", "mfe");
		h.put("język jawi", "mfa");
		h.put("średnioirlandzki", "mga");
		h.put("nias", "nia");
		h.put("mende", "men");
		h.put("język nilamba", "nim");
		h.put("hassanija", "mey");
		h.put("język wu", "wuu");
		h.put("język wutung", "wut");
		h.put("język motu", "meu");
		h.put("język niwchijski", "niv");
		h.put("język niue", "niu");
		h.put("niue", "niu");
		h.put("meru", "mer");
		h.put("język meru", "mer");
		h.put("język aiwo", "nfl");
		h.put("język moksza", "mdf");
		h.put("moksha", "mdf");
		h.put("maba", "mde");
		h.put("język mbati", "mdn");
		h.put("mandar", "mdr");
		h.put("język maria", "mds");
		h.put("język ngombe", "ngc");
		h.put("język ngulu", "ngp");
		h.put("jola-fonyi", "dyo");
		h.put("wolof", "wol");
		h.put("dyula", "dyu");
		h.put("język diula", "dyu");
		h.put("język wogamusin", "wog");
		h.put("język makaa", "mcp");
		h.put("język nanggu", "ngr");
		h.put("dazaga", "dzg");
		h.put("język warapu", "wra");
		h.put("język ndebele północny", "nde");
		h.put("ndebele północny", "nde");
		h.put("dzongkha", "dzo");
		h.put("dzongkha", "dzo");
		h.put("język mbo", "mbo");
		h.put("język ndonga", "ndo");
		h.put("ndonga", "ndo");
		h.put("język mbama", "mbm");
		h.put("język waris", "wrs");
		h.put("język dolnosaksoński", "nds");
		h.put("język dolnoniemiecki", "nds");
		h.put("dolnosaksoński", "nds");
		h.put("język nedebang", "nec");
		h.put("magahi", "mag");
		h.put("język magahi", "mag");
		h.put("mafa", "maf");
		h.put("madurajski", "mad");
		h.put("język madurski", "mad");
		h.put("mandingo", "man");
		h.put("nepalski", "nep");
		h.put("język nepalski", "nep");
		h.put("malajalam", "mal");
		h.put("język malajalam", "mal");
		h.put("język makasarski", "mak");
		h.put("makasar", "mak");
		h.put("język nete", "net");
		h.put("marshall", "mah");
		h.put("język marszalski", "mah");
		h.put("język maithili", "mai");
		h.put("maithili", "mai");
		h.put("język newarski", "new");
		h.put("newarski", "new");
		h.put("język marathi", "mar");
		h.put("marathi", "mar");
		h.put("masajski", "mas");
		h.put("język makian zachodni", "mqs");
		h.put("język północny sotho", "nso");
		h.put("sotho północny", "nso");
		h.put("efik", "efi");
		h.put("język nsenga", "nse");
		h.put("język ngurmbur", "nrx");
		h.put("starożytny egipski", "egy");
		h.put("język emilijski", "egl");
		h.put("mossi", "mos");
		h.put("język mossi", "mos");
		h.put("n’ko", "nqo");
		h.put("język ndom", "nqm");
		h.put("języki mongolskie", "mon");
		h.put("mongolski", "mon");
		h.put("język mohawk", "moh");
		h.put("mohawk", "moh");
		h.put("język mon", "mnw");
		h.put("język mansyjski", "mns");
		h.put("język norn", "nrn");
		h.put("język minbei", "mnp");
		h.put("język północnopiceński", "nrp");
		h.put("język mundżański", "mnj");
		h.put("manipuryjski", "mni");
		h.put("język manipuri", "mni");
		h.put("język mandinka", "mnk");
		h.put("manchu", "mnc");
		h.put("język mandżurski", "mnc");
		h.put("nogajski", "nog");
		h.put("język nogajski", "nog");
		h.put("język północnotajski", "nod");
		h.put("język nimadi", "noe");
		h.put("bokmål", "nob");
		h.put("norweski bokmål", "nob");
		h.put("język staronordyjski", "non");
		h.put("staronordyjski", "non");
		h.put("język huroński", "wya");
		h.put("maltański", "mlt");
		h.put("język maltański", "mlt");
		h.put("nynorsk", "nno");
		h.put("norweski nynorsk", "nno");
		h.put("język malgaski", "mlg");
		h.put("malgaski", "mlg");
		h.put("novial", "nov");
		h.put("embu", "ebu");
		h.put("język embu", "ebu");
		h.put("język numanggang", "nop");
		h.put("język norweski", "nor");
		h.put("norweski", "nor");
		h.put("języki nyulnyulańskie", "wwr");
		h.put("język maiwa", "mkz");
		h.put("dhatki", "mki");
		h.put("ngumba", "nmg");
		h.put("język macedoński", "mkd");
		h.put("macedoński", "mkd");
		h.put("język nihali", "nll");
		h.put("język eteocypryjski", "ecy");
		h.put("język mongorski", "mjg");
		h.put("ngiemboon", "nnh");
		h.put("minangkabu", "min");
		h.put("język minangkabau", "min");
		h.put("język !xóõ", "nmn");
		h.put("etnolekt wilamowicki", "wym");
		h.put("języki nyulnyulańskie", "nmp");
		h.put("język miskito", "miq");
		h.put("inny język", "mis");
		h.put("język kalasza-ala", "wbk");
		h.put("język dalmatyński", "dlm");
		h.put("myene", "mye");
		h.put("język myene", "mye");
		h.put("język birmański", "mya");
		h.put("birmański", "mya");
		h.put("język wachański", "wbl");
		h.put("język erzja", "myv");
		h.put("erzya", "myv");
		h.put("język pirahã", "myp");
		h.put("język masaba", "myx");
		h.put("język dani zachodni", "dnw");
		h.put("nowozelandzki język migowy", "nzs");
		h.put("język wadaginam", "wdg");
		h.put("nzema", "nzi");
		h.put("język dogri", "doi");
		h.put("dogri", "doi");
		h.put("język mirandyjski", "mwl");
		h.put("mirandese", "mwl");
		h.put("niamwezi", "nym");
		h.put("język nyankole", "nyn");
		h.put("nyankole", "nyn");
		h.put("język nyoro", "nyo");
		h.put("nyoro", "nyo");
		h.put("język marwari", "mwr");
		h.put("marwari", "mwr");
		h.put("język dungański", "dng");
		h.put("język konde", "nyy");
		h.put("język kamtok", "wes");
		h.put("język mewari", "mtr");
		h.put("njandża", "nya");
		h.put("język cziczewa", "nya");
		h.put("newarski klasyczny", "nwc");
		h.put("mundang", "mua");
		h.put("wiele języków", "mul");
		h.put("creek", "mus");
		h.put("język krik", "mus");
		h.put("dogrib", "dgr");
		h.put("język malwi", "mup");
		h.put("dżerma", "dje");
		h.put("język dżerma", "dje");
		h.put("język ndyuka", "djk");
		h.put("język maori", "mri");
		h.put("maoryjski", "mri");
		h.put("język digo", "dig");
		h.put("dinka", "din");
		h.put("wysokoalemański", "wae");
		h.put("język molof", "msl");
		h.put("język nuer", "nus");
		h.put("nuer", "nus");
		h.put("język malediwski", "div");
		h.put("malediwski", "div");
		h.put("walamo", "wal");
		h.put("język massachusett", "wam");
		h.put("język warajski", "war");
		h.put("waraj", "war");
		h.put("washo", "was");
		h.put("ndebele południowy", "nbl");
		h.put("język ndebele południowy", "nbl");
		h.put("średniowieczny niderlandzki", "dum");
		h.put("język naxi", "nbf");
		h.put("duala", "dua");
		h.put("język duala", "dua");
		h.put("język naurański", "nau");
		h.put("nauru", "nau");
		h.put("język nawaho", "nav");
		h.put("nawaho", "nav");
		h.put("waloński", "wln");
		h.put("język waloński", "wln");
		h.put("język dagurski", "dta");
		h.put("neapolitański", "nap");
		h.put("język minnański", "nan");
		h.put("język nasioi", "nas");
		h.put("nama", "naq");
		h.put("naga pidgin", "nag");
		h.put("język oksytański", "oci");
		h.put("prowansalski", "oci");
		h.put("język starochiński", "och");
		h.put("język muani", "wmw");
		h.put("język wambon", "wms");
		h.put("język moabicki", "obm");
		h.put("język mazanderański", "mzn");
		h.put("dolnołużycki", "dsb");
		h.put("język dolnołużycki", "dsb");
		h.put("język dororo", "drr");
		h.put("język winnebago", "win");
		h.put("język wiru", "wiu");
		h.put("język wenecki", "vec");
		h.put("język yupik środkowy", "esu");
		h.put("estoński", "est");
		h.put("język estoński", "est");
		h.put("język etruski", "ett");
		h.put("język eton", "eto");
		h.put("język baskijski", "eus");
		h.put("baskijski", "eus");
		h.put("język wepski", "vep");
		h.put("język eweński", "eve");
		h.put("venda", "ven");
		h.put("język venda", "ven");
		h.put("język ewenkijski", "evn");
		h.put("język ewe", "ewe");
		h.put("ewe", "ewe");
		h.put("ewondo", "ewo");
		h.put("język yaunde", "ewo");
		h.put("język wietnamski", "vie");
		h.put("wietnamski", "vie");
		h.put("język estremadurski", "ext");
		h.put("język eyak", "eya");
		h.put("ekajuk", "eka");
		h.put("uzbecki", "uzn");
		h.put("język uzbecki", "uzb");
		h.put("język elamicki", "elx");
		h.put("elamicki", "elx");
		h.put("grecki", "ell");
		h.put("język nowogrecki", "ell");
		h.put("język angielski", "eng");
		h.put("angielski", "eng");
		h.put("średnioangielski", "enm");
		h.put("język średnioangielski", "enm");
		h.put("język enga", "enq");
		h.put("esperanto", "epo");
		h.put("esperanto", "epo");
		h.put("język vai", "vai");
		h.put("wai", "vai");
		h.put("vunjo", "vun");
		h.put("fidżijski", "fij");
		h.put("język fidżyjski", "fij");
		h.put("język filipiński", "fil");
		h.put("filipino", "fil");
		h.put("fiński", "fin");
		h.put("język fiński", "fin");
		h.put("język fipa", "fip");
		h.put("meänkieli", "fit");
		h.put("język flamandzki", "vls");
		h.put("język makua", "vmw");
		h.put("wotiacki", "vot");
		h.put("język wotycki", "vot");
		h.put("volapük", "vol");
		h.put("volapuk", "vol");
		h.put("język fang", "fan");
		h.put("fang", "fan");
		h.put("farerski", "fao");
		h.put("fanti", "fat");
		h.put("perski", "fas");
		h.put("język perski", "fas");
		h.put("język fasu", "faa");
		h.put("język faita", "faj");
		h.put("język võro", "vro");
		h.put("język ubyski", "uby");
		h.put("język ugarycki", "uga");
		h.put("ugarycki", "uga");
		h.put("język udyjski", "udi");
		h.put("język udmurcki", "udm");
		h.put("udmurcki", "udm");
		h.put("język tseltal", "tzh");
		h.put("centralnomarokański tamazight", "tzm");
		h.put("tuwiński", "tyv");
		h.put("język tuwiński", "tyv");
		h.put("fon", "fon");
		h.put("język tauya", "tya");
		h.put("język tangucki", "txg");
		h.put("język tracki", "txh");
		h.put("tasawaq", "twq");
		h.put("twents", "twd");
		h.put("twi", "twi");
		h.put("język twi", "twi");
		h.put("język tai don", "twh");
		h.put("język tuvalu", "tvl");
		h.put("tuvalu", "tvl");
		h.put("język tidore", "tvo");
		h.put("fulani", "ful");
		h.put("język ful", "ful");
		h.put("język friulski", "fur");
		h.put("friulijski", "fur");
		h.put("średniofrancuski", "frm");
		h.put("francuski", "fra");
		h.put("język francuski", "fra");
		h.put("język zachodniofryzyjski", "fry");
		h.put("zachodniofryzyjski", "fry");
		h.put("fryzyjski wschodni", "frs");
		h.put("północnofryzyjski", "frr");
		h.put("język północnofryzyjski", "frr");
		h.put("starofrancuski", "fro");
		h.put("język starofrancuski", "fro");
		h.put("gilbertański", "gil");
		h.put("język kiribati", "gil");
		h.put("język ginuchijski", "gin");
		h.put("język gogodala", "ggw");
		h.put("urdu", "urd");
		h.put("język urdu", "urd");
		h.put("gocki", "got");
		h.put("język gocki", "got");
		h.put("dialekt groningski", "gos");
		h.put("gorontalo", "gor");
		h.put("język gondi", "gon");
		h.put("gondi", "gon");
		h.put("staro-wysoko-niemiecki", "goh");
		h.put("język staro-wysoko-niemiecki", "goh");
		h.put("język gogo", "gog");
		h.put("język gunijandi", "gni");
		h.put("język guanczów", "gnc");
		h.put("średnio-wysoko-niemiecki", "gmh");
		h.put("język średnio-wysoko-niemiecki", "gmh");
		h.put("język mykeński", "gmy");
		h.put("galisyjski", "glg");
		h.put("język galicyjski", "glg");
		h.put("język guliguli", "gli");
		h.put("język giliański", "glk");
		h.put("szkocki gaelicki", "gla");
		h.put("irlandzki", "gle");
		h.put("język irlandzki", "gle");
		h.put("manx", "glv");
		h.put("ukraiński", "ukr");
		h.put("język ukraiński", "ukr");
		h.put("język garhwali", "gbm");
		h.put("gbaya", "gba");
		h.put("język usku", "ulf");
		h.put("język meriam", "ulk");
		h.put("unserdeutsch", "uln");
		h.put("język gan", "gan");
		h.put("gayo", "gay");
		h.put("język kenati", "gat");
		h.put("ujgurski", "uig");
		h.put("język ujgurski", "uig");
		h.put("język ga", "gaa");
		h.put("ga", "gaa");
		h.put("język gagauski", "gag");
		h.put("język gafat", "gft");
		h.put("język gyyz", "gez");
		h.put("gyyz", "gez");
		h.put("język umbugarla", "umr");
		h.put("huttrisch", "geh");
		h.put("umbundu", "umb");
		h.put("język umbundu", "umb");
		h.put("język laal", "gdm");
		h.put("język godoberyjski", "gdo");
		h.put("nieznany język", "und");
		h.put("język kreolski gujany francuskiej", "gcr");
		h.put("tatarski", "tat");
		h.put("język tatarski", "tat");
		h.put("tahitański", "tah");
		h.put("język tahitański", "tah");
		h.put("język tagoi", "tag");
		h.put("język tamilski", "tam");
		h.put("tamilski", "tam");
		h.put("język haya", "hay");
		h.put("język hawajski", "haw");
		h.put("hawajski", "haw");
		h.put("język tulu", "tcy");
		h.put("język tai neua", "tdd");
		h.put("haida", "hai");
		h.put("język tanah merah", "tcm");
		h.put("język hakka", "hak");
		h.put("język harari", "har");
		h.put("język hausa", "hau");
		h.put("hausa", "hau");
		h.put("haitański", "hat");
		h.put("język kreolski haitański", "hat");
		h.put("język kreolski gujański", "gyn");
		h.put("język tabasarański", "tab");
		h.put("syriacki", "syc");
		h.put("język syryjski", "syc");
		h.put("język guarani", "gug");
		h.put("syryjski", "syr");
		h.put("język gudźarati", "guj");
		h.put("gudźaracki", "guj");
		h.put("język gusii", "guz");
		h.put("gusii", "guz");
		h.put("język seloński", "sxl");
		h.put("gwichʼin", "gwi");
		h.put("język gwere", "gwr");
		h.put("etnolekt śląski", "szl");
		h.put("język fryzyjski saterlandzki", "stq");
		h.put("sukuma", "suk");
		h.put("język sukuma", "suk");
		h.put("język suki", "sui");
		h.put("język sulka", "sua");
		h.put("siswati", "ssw");
		h.put("język suazi", "ssw");
		h.put("afar-saho", "ssy");
		h.put("język sentinel", "std");
		h.put("język shelta", "sth");
		h.put("język grecki klasyczny", "grc");
		h.put("starogrecki", "grc");
		h.put("grebo", "grb");
		h.put("język garo", "grt");
		h.put("guarani", "grn");
		h.put("język savosavo", "svs");
		h.put("suahili", "swh");
		h.put("szwedzki", "swe");
		h.put("język szwedzki", "swe");
		h.put("kongijski suahili", "swc");
		h.put("język maore", "swb");
		h.put("komoryjski", "swb");
		h.put("suahili", "swa");
		h.put("szwajcarski niemiecki", "gsw");
		h.put("gwary schwyzertüütsch", "gsw");
		h.put("sumeryjski", "sux");
		h.put("język sumeryjski", "sux");
		h.put("susu", "sus");
		h.put("sundajski", "sun");
		h.put("język sundajski", "sun");
		h.put("język swański", "sva");
		h.put("taroko", "trv");
		h.put("język tswa", "tsc");
		h.put("język turunggare", "trt");
		h.put("język kokborok", "trp");
		h.put("język tregami", "trm");
		h.put("język ho", "hoc");
		h.put("tshangla", "tsj");
		h.put("tsimshian", "tsi");
		h.put("język tsogo", "tsv");
		h.put("język tsonga", "tso");
		h.put("tsonga", "tso");
		h.put("język tswana", "tsn");
		h.put("setswana", "tsn");
		h.put("język hopi", "hop");
		h.put("riograndeser hunsrückisch", "hrx");
		h.put("górnołużycki", "hsb");
		h.put("język górnołużycki", "hsb");
		h.put("język isan", "tts");
		h.put("język chorwacki", "hrv");
		h.put("chorwacki", "hrv");
		h.put("język turkmeński", "tuk");
		h.put("turkmeński", "tuk");
		h.put("język tumbuka", "tum");
		h.put("tumbuka", "tum");
		h.put("turecki", "tur");
		h.put("język turecki", "tur");
		h.put("język hunde", "hke");
		h.put("język tonga", "ton");
		h.put("tonga", "ton");
		h.put("tonga (niasa)", "tog");
		h.put("język tonga", "toi");
		h.put("karaibskie hindustani", "hns");
		h.put("tok pisin", "tpi");
		h.put("tok pisin", "tpi");
		h.put("język ćhattisgarhi", "hne");
		h.put("hiri motu", "hmo");
		h.put("hiri motu", "hmo");
		h.put("hmongijski", "hmn");
		h.put("język tiwi", "tiw");
		h.put("tiw", "tiv");
		h.put("język tiw", "tiv");
		h.put("tokelau", "tkl");
		h.put("język tokelau", "tkl");
		h.put("język cachurski", "tkr");
		h.put("język hixkaryana", "hix");
		h.put("język tobelo", "tlb");
		h.put("język tofamna", "tlg");
		h.put("język telefol", "tlf");
		h.put("klingoński", "tlh");
		h.put("język klingoński", "tlh");
		h.put("język tlingit", "tli");
		h.put("tlingit", "tli");
		h.put("język tetela", "tll");
		h.put("tamaszek", "tmh");
		h.put("język tamaszek", "tmh");
		h.put("język hiligaynon", "hil");
		h.put("hiligajnon", "hil");
		h.put("himachali", "him");
		h.put("język samarokena", "tmj");
		h.put("język judeo-aramejski", "tmr");
		h.put("hindi fidżyjskie", "hif");
		h.put("hetycki", "hit");
		h.put("język hetycki", "hit");
		h.put("hindi", "hin");
		h.put("tetum", "tet");
		h.put("tetum", "tet");
		h.put("ateso", "teo");
		h.put("tereno", "ter");
		h.put("język telugu", "tel");
		h.put("telugu", "tel");
		h.put("temne", "tem");
		h.put("serbsko-chorwacki", "hbs");
		h.put("język serbsko-chorwacki", "hbs");
		h.put("język heiban", "hbn");
		h.put("tagalski", "tgl");
		h.put("język tagalog", "tgl");
		h.put("język tadżycki", "tgk");
		h.put("tadżycki", "tgk");
		h.put("herero", "her");
		h.put("język herero", "her");
		h.put("tajski", "tha");
		h.put("język tajski", "tha");
		h.put("język hadija", "hdy");
		h.put("język tindyjski", "tin");
		h.put("tigrinia", "tir");
		h.put("język tigrinia", "tir");
		h.put("język hehe", "heh");
		h.put("hebrajski", "heb");
		h.put("język tifal", "tif");
		h.put("język tigre", "tig");
		h.put("tigre", "tig");
		h.put("ngambay", "sba");
		h.put("język saurasztryjski", "saz");
		h.put("język sawuy", "saw");
		h.put("sasak", "sas");
		h.put("santali", "sat");
		h.put("sanskryt", "san");
		h.put("sanskryt", "san");
		h.put("samburu", "saq");
		h.put("samarytański aramejski", "sam");
		h.put("język sango", "sag");
		h.put("sango", "sag");
		h.put("język jakucki", "sah");
		h.put("jakucki", "sah");
		h.put("sandawe", "sad");
		h.put("ido", "ido");
		h.put("ido", "ido");
		h.put("ibanag", "iba");
		h.put("język iban", "iba");
		h.put("język ibibio", "ibb");
		h.put("ibibio", "ibb");
		h.put("język purari", "iar");
		h.put("język igbo", "ibo");
		h.put("igbo", "ibo");
		h.put("język okinawski", "ryu");
		h.put("język amba", "rwm");
		h.put("rwa", "rwk");
		h.put("język rosyjski", "rus");
		h.put("rosyjski", "rus");
		h.put("język meglenorumuński", "ruq");
		h.put("język arumuński", "rup");
		h.put("arumuński", "rup");
		h.put("język rutulski", "rut");
		h.put("ormiański", "hye");
		h.put("rundi", "run");
		h.put("język rundi", "run");
		h.put("język istrorumuński", "ruo");
		h.put("język rusiński", "rue");
		h.put("język ruguru", "ruf");
		h.put("hupa", "hup");
		h.put("język węgierski", "hun");
		h.put("węgierski", "hun");
		h.put("język chunzybski", "huz");
		h.put("język rotumański", "rtm");
		h.put("język kreolski hawajski", "hwc");
		h.put("język xiang", "hsn");
		h.put("język hadza", "hts");
		h.put("język huli", "hui");
		h.put("język sora", "srb");
		h.put("dialekt logudorski", "src");
		h.put("język sardyński", "srd");
		h.put("sardyński", "srd");
		h.put("albański", "sqi");
		h.put("język albański", "sqi");
		h.put("język serbski", "srp");
		h.put("serbski", "srp");
		h.put("dialekt kampidański", "sro");
		h.put("język serer", "srr");
		h.put("serer", "srr");
		h.put("język sarikoli", "srh");
		h.put("sranan tongo", "srn");
		h.put("sranan tongo", "srn");
		h.put("język itelmeński", "itl");
		h.put("język saramakański", "srm");
		h.put("język judeo-włoski", "itk");
		h.put("język hiszpański", "spa");
		h.put("hiszpański", "spa");
		h.put("włoski", "ita");
		h.put("język włoski", "ita");
		h.put("sotho południowy", "sot");
		h.put("język sotho", "sot");
		h.put("język południowotajski", "sou");
		h.put("język somalijski", "som");
		h.put("somalijski", "som");
		h.put("język istriocki", "ist");
		h.put("sogdyjski", "sog");
		h.put("język sogdyjski", "sog");
		h.put("islandzki", "isl");
		h.put("język islandzki", "isl");
		h.put("język iszkaszmi", "isk");
		h.put("język iraku", "irk");
		h.put("samoański", "smo");
		h.put("język samoański", "smo");
		h.put("lapoński inari", "smn");
		h.put("język inari", "smn");
		h.put("lapoński skolt", "sms");
		h.put("język sumbawa", "smw");
		h.put("lapoński południowy", "sma");
		h.put("język południowolapoński", "sma");
		h.put("język północnolapoński", "sme");
		h.put("lapoński północny", "sme");
		h.put("język lule", "smj");
		h.put("lapoński lule", "smj");
		h.put("język sangu", "snq");
		h.put("język shona", "sna");
		h.put("szona", "sna");
		h.put("sindhi", "snd");
		h.put("sindhi", "snd");
		h.put("język soninke", "snk");
		h.put("soninke", "snk");
		h.put("inupiak", "ipk");
		h.put("język chiwere", "iow");
		h.put("język sakata", "skt");
		h.put("słoweński", "slv");
		h.put("język słoweński", "slv");
		h.put("interlingua", "ina");
		h.put("interlingua", "ina");
		h.put("język indonezyjski", "ind");
		h.put("indonezyjski", "ind");
		h.put("dialekt śląski języka niemieckiego", "sli");
		h.put("inguski", "inh");
		h.put("język inguski", "inh");
		h.put("słowacki", "slk");
		h.put("język słowacki", "slk");
		h.put("język akkala", "sia");
		h.put("język sidamo", "sid");
		h.put("sidamo", "sid");
		h.put("arabski (czad)", "shu");
		h.put("syngaleski", "sin");
		h.put("język syngaleski", "sin");
		h.put("język dandzongka", "sip");
		h.put("interlingue", "ile");
		h.put("occidental", "ile");
		h.put("ilokano", "ilo");
		h.put("język iloko", "ilo");
		h.put("sindarin", "sjn");
		h.put("inuktitut", "iku");
		h.put("inuktitut", "iku");
		h.put("język szugnański", "sgh");
		h.put("staroirlandzki", "sga");
		h.put("język staroirlandzki", "sga");
		h.put("język żmudzki", "sgs");
		h.put("język szan", "shn");
		h.put("shan", "shn");
		h.put("język szylluk", "shk");
		h.put("tashelhiyt", "shi");
		h.put("język tashelhiyt", "shi");
		h.put("dialekt gallurski", "sdn");
		h.put("język szuadit", "sdt");
		h.put("syczuański", "iii");
		h.put("język nuosu", "iii");
		h.put("seneka", "see");
		h.put("język seri", "sei");
		h.put("sena", "seh");
		h.put("selkupski", "sel");
		h.put("język selkupski", "sel");
		h.put("język sentani", "set");
		h.put("język glosa", "igs");
		h.put("koyraboro senni", "ses");
		h.put("sabinowie", "sbv");
		h.put("sangu", "sbp");
		h.put("język chut", "scb");
		h.put("język santyjski", "sce");
		h.put("język sycylijski", "scn");
		h.put("sycylijski", "scn");
		h.put("szkocki", "sco");
		h.put("język scots", "sco");
		h.put("dialekt sassarski", "sdc");
		
		// Manual additions to lexvo
		h.put("holenderski", "nld");
		h.put("afrykanerski", "afr");
		h.put("chiński standardowy", "zho");
		h.put("wilamowski", "wim");
		h.put("fryzyjski", "fry");
		h.put("dolnośląski", "sli");
		h.put("śląski", "szl");
	}

	public static String threeLettersCode(String s) {
		if(s == null || s.equals("")) return null;

        s= s.trim();
        s=s.toLowerCase();
        if (h.containsKey(s)) {
            s = h.get(s);
        } else if (h.containsKey("język " + s)) {
            s = h.get("język " + s);
        } else {
            s = s.replace("(", "");
            s = s.replace(")", "");
            s = h.get(s);
        }
        return LangTools.getCode(s);
	}
}
