#!/bin/bash
# extrait les définitions par terme 
# format d'entrée : Gilles
# sorties : file.Noyau : toutes les définitions d'un terme et leur pos tag (non trié)

if (( $# != "1" )) ; then
echo "usage : de_extract-defNoyau [file]" 
exit
fi

#if (( $1 == "-f" )) ; then  
#L="#fra"
#elif (( $1 == "-e" )) ; then
#L="#eng"
#elif (( $1 == "-d")) ; then
#L="#deu"
#fi

# extraction des termes définis (origine) et des définitions destinations avec le pos associé

awk '{ gsub(/\|/, " ") ; 
	   if ($1 == "-O-" && $2 == "#deu") { etat = 1 ; print $0 ;} 
	   else if (etat == 1 && $1 != "-O-")  { print $0 ; }  
	   else { etat = 0 ; } ;  }' $1 | 
egrep '(^[ ,	]*-O- #eng|^[ ,	]*-D- #def|^[ ,	]*-D- #pos)' | 
awk '{ gsub(/#deu/, "") ; gsub(/#def/, "") ; gsub(/-D- #pos/, "-pos-") ; gsub(/#{/,""); gsub(/}#/,""); print ;}' > $1.Noyau