#!/bin/bash
# extrait les termes définis dans wiktionnary dont on a récupéré les définitions
# format d'entrée : Gilles
# sorties : file.terme -> liste des termes (dernière ligne du fichier : nombre de termes extraits)

if (( $# != "2" )) ; then
echo "usage : extract-terme [-f | -e | -d] [file]" 
echo "-f : french  -e : english  -d : deutsch" 
exit
fi

if [[ $1 == "-f" ]] ; then  
L="#fra"
elif [[ $1 == "-e" ]] ; then
L="#eng"
elif [[ $1 == "-d" ]] ; then
L="#deu"
fi

# extraction des termes puis nettoyage du format "Gilles" et de la ponctuation, suppression termes doublons
egrep '^[ ,	]*-[D|O]- '+$L+'\|' $2 | awk '{ gsub(/[ ]*-[D|O]- /,""); 
										 gsub(/#.*\|/, "") ;
										 gsub(/#{/,""); gsub(/}#/,""); 
										 gsub(/’/," "); 
										 gsub(/[.|,|;]/,"") ; print }' | sort -u > $2.terme 


# comptage des terme extraits 
wc -l $2.terme >> $2.terme