/**
 * 
 */
package org.getalp.dbnary.por;

import java.util.HashMap;

import org.getalp.dbnary.LangTools;

/**
 * @author Mariam
 *
 */
public class PortugueseLangToCode extends LangTools {
	static HashMap<String,String> h = new HashMap<String,String>();
	static {
		h.put("Abecásio","ab");
		h.put("Acadiano","akk");
		h.put("Acenês","ace");
		h.put("Afar","aa");
		h.put("Africâner","af");
		h.put("Aimará","ay");
		h.put("Aino","ain");
		h.put("Akan","ak");
		h.put("Albanês","sq");
		h.put("Alemânico","gsw");
		h.put("Alemão","de");
		h.put("Aleúte","ale");
		h.put("Altaico","alt");
		h.put("Alto Alemão Antigo","goh");
		h.put("Alto Alemão Médio","gmh");
		h.put("Amárico","am");
		h.put("Árabe","ar");
		h.put("Aragonês","an");
		h.put("Aramaico","arc");
		h.put("Arapaho","arp");
		h.put("Araucano","arn");
		h.put("Armênio","hy");
		h.put("Aromeno","rup");
		h.put("Aruaque","arw");
		h.put("Assamês","as");
		h.put("Asturiano","ast");
		h.put("Avárico","av");
		h.put("Avéstico","ae");
		h.put("Azerbaijano","az");
		h.put("Baixo Saxão","nds");
		h.put("Balinês","ban");
		h.put("Balúchi","bal");
		h.put("Bambara","bm");
		h.put("Basa","bas");
		h.put("Basco","eu");
		h.put("Basquir","ba");
		h.put("Bemba","bem");
		h.put("Bengali","bn");
		h.put("Bhojpuri","bho");
		h.put("Bicolano","bik");
		h.put("Bielorrusso","be");
		h.put("Birmanês","my");
		h.put("Bislamá","bi");
		h.put("Bósnio","bs");
		h.put("Bretão","br");
		h.put("Buginês","bug");
		h.put("Búlgaro","bg");
		h.put("Buriate","bua");
		h.put("Cabardino","kbd");
		h.put("Cabila","kab");
		h.put("Cachúbio","csb");
		h.put("Caddo","cad");
		h.put("Calmuco","xal");
		h.put("Cambojano","km");
		h.put("Canarês","kn");
		h.put("Caracalpaque","kaa");
		h.put("Carachai-Balcar","krc");
		h.put("Carélio","krl");
		h.put("Catalão","ca");
		h.put("Caxemira","ks");
		h.put("Cazaque","kk");
		h.put("Cebuano","ceb");
		h.put("Chagatai","chg");
		h.put("Chamorro","ch");
		h.put("Checheno","ce");
		h.put("Checo","cs");
		h.put("Cherokee","chr");
		h.put("Cheyenne","chy");
		h.put("Chibcha/Muisca","chb");
		h.put("Chinês","zh");
		h.put("Chipewyan","chp");
		h.put("Choctaw","cho");
		h.put("Chona","sn");
		h.put("Cingalês","si");
		h.put("Circassiano","ady");
		h.put("Concani","kok");
		h.put("Copta","cop");
		h.put("Coreano","ko");
		h.put("Córnico","kw");
		h.put("Corso","co");
		h.put("Cree","cr");
		h.put("Creek","mus");
		h.put("Croata","hr");
		h.put("Cuanhama","kj");
		h.put("Curdo","ku");
		h.put("Dakota","dak");
		h.put("Dano-norueguês","nb");
		h.put("Dargínico","dar");
		h.put("Delaware","del");
		h.put("Dinamarquês","da");
		h.put("Divehi","dv");
		h.put("Duala","dua");
		h.put("Egípcio","egy");
		h.put("Elamita","elx");
		h.put("Erzya","myv");
		h.put("Escocês","sco");
		h.put("Eslavo Eclesiástico","cu");
		h.put("Eslovaco","sk");
		h.put("Esloveno","sl");
		h.put("Espanhol","es");
		h.put("Esperanto","eo");
		h.put("Estoniano","et");
		h.put("Fenício","phn");
		h.put("Feroês","fo");
		h.put("Fijiano","fj");
		h.put("Filipino","fil");
		h.put("Finlandês","fi");
		h.put("Francês","fr");
		h.put("Francês Antigo","fro");
		h.put("Francês Médio","frm");
		h.put("Frísio","fy");
		h.put("Frísio Setentrional","frr");
		h.put("Friuliano","fur");
		h.put("Fula","ff");
		h.put("Ga","gaa");
		h.put("Gaélico Escocês","gd");
		h.put("Galego","gl");
		h.put("Galês","cy");
		h.put("Gayo","gay");
		h.put("Ge'ez","gez");
		h.put("Georgiano","ka");
		h.put("Gilbertês","gil");
		h.put("Gótico","got");
		h.put("Grego","el");
		h.put("Grego Antigo","grc");
		h.put("Groenlandês","kl");
		h.put("Guarani","gn");
		h.put("Guzerate","gu");
		h.put("Haida","hai");
		h.put("Haitiano","ht");
		h.put("Hauçá","ha");
		h.put("Havaiano","haw");
		h.put("Hebraico","he");
		h.put("Hereró","hz");
		h.put("Hiligaynon","hil");
		h.put("Hindi","hi");
		h.put("Hiri Motu","ho");
		h.put("Hitita","hit");
		h.put("Hmong","hmn");
		h.put("Holandês","nl");
		h.put("Holandês Médio","dum");
		h.put("Húngaro","hu");
		h.put("Iacute","sah");
		h.put("Iban","iba");
		h.put("Ibo","ig");
		h.put("Ido","io");
		h.put("Iídiche","yi");
		h.put("Ilocano","ilo");
		h.put("Indonésio","id");
		h.put("Inglês","en");
		h.put("Inglês Antigo","ang");
		h.put("Inglês Médio","enm");
		h.put("Inguche","inh");
		h.put("Interlíngua","ia");
		h.put("Interlíngue","ie");
		h.put("Inuktitut","iu");
		h.put("Inupiaque","ik");
		h.put("Iorubá","yo");
		h.put("Irlandês","ga");
		h.put("Irlandês Antigo","sga");
		h.put("Islandês","is");
		h.put("Italiano","it");
		h.put("Japonês","ja");
		h.put("Javanês","jv");
		h.put("Jeje","ee");
		h.put("Jingpo","kac");
		h.put("Kamba","kam");
		h.put("Kanuri","kr");
		h.put("Khasi","kha");
		h.put("Khotanês","kho");
		h.put("Kikongo","kg");
		h.put("Kikuyo","ki");
		h.put("Klingon","tlh");
		h.put("Komi","kv");
		h.put("Kosraeano","kos");
		h.put("Kumyk","kum");
		h.put("Ladino","lad");
		h.put("Laociano","lo");
		h.put("Latim","la");
		h.put("Letão","lv");
		h.put("Lezguiano","lez");
		h.put("Limburguês","li");
		h.put("Lingala","ln");
		h.put("Lituano","lt");
		h.put("Lojban","jbo");
		h.put("Luganda","lg");
		h.put("Luo","luo");
		h.put("Lushai","lus");
		h.put("Luxemburguês","lb");
		h.put("Macedônio","mk");
		h.put("Madurês","mad");
		h.put("Makasar","mak");
		h.put("Malaiala","ml");
		h.put("Malaio","ms");
		h.put("Malgaxe","mg");
		h.put("Maltês","mt");
		h.put("Manchu","mnc");
		h.put("Manipuri","mni");
		h.put("Manquês","gv");
		h.put("Maori","mi");
		h.put("Marati","mr");
		h.put("Mari","chm");
		h.put("Marshalês","mh");
		h.put("Massai","mas");
		h.put("Micmac","mic");
		h.put("Minangkabau","min");
		h.put("Mirandês","mwl");
		h.put("Mohawk","moh");
		h.put("Moksha","mdf");
		h.put("Moldavo","mo");
		h.put("Mongol","mn");
		h.put("Napolitano","nap");
		h.put("Nauruano","na");
		h.put("Navajo","nv");
		h.put("Ndebele Meridional","nr");
		h.put("Ndebele Setentrional","nd");
		h.put("Ndonga","ng");
		h.put("Nepalês","ne");
		h.put("Newari","new");
		h.put("Nias","nia");
		h.put("Niue","niu");
		h.put("Nogai","nog");
		h.put("Nórdico Antigo","non");
		h.put("Norueguês","no");
		h.put("Novo Norueguês","nn");
		h.put("Nyamwezi","nym");
		h.put("Nyanja","ny");
		h.put("Occitano","oc");
		h.put("Ojibua","oj");
		h.put("Oriá","or");
		h.put("Oromo","om");
		h.put("Osseta","os");
		h.put("Palauano","pau");
		h.put("Pali","pi");
		h.put("Pampangan","pam");
		h.put("Pangasinan","pag");
		h.put("Papiamento","pap");
		h.put("Pashtu","ps");
		h.put("Persa","fa");
		h.put("Persa Antigo","peo");
		h.put("Pohnpeiano","pon");
		h.put("Polonês","pl");
		h.put("Português","pt");
		h.put("Provençal Antigo","pro");
		h.put("Punjabi","pa");
		h.put("Quéchua","qu");
		h.put("Quimbundo","kmb");
		h.put("Quirguiz","ky");
		h.put("Rajastani","raj");
		h.put("Rapanui","rap");
		h.put("Rarotonga","rar");
		h.put("Romanche","rm");
		h.put("Romani","rom");
		h.put("Romeno","ro");
		h.put("Ruanda","rw");
		h.put("Rundi","rn");
		h.put("Russo","ru");
		h.put("Sami Inari","smn");
		h.put("Sami Lule","smj");
		h.put("Sami Meridional","sma");
		h.put("Sami Setentrional","se");
		h.put("Sami Skolt","sms");
		h.put("Samoano","sm");
		h.put("Sango","sg");
		h.put("Sânscrito","sa");
		h.put("Santali","sat");
		h.put("Sardo","sc");
		h.put("Sasaque","sas");
		h.put("Sepédi","nso");
		h.put("Sérvio","sr");
		h.put("Servocroata","sh");
		h.put("Sesoto","st");
		h.put("Shan","shn");
		h.put("Siciliano","scn");
		h.put("Siksika","bla");
		h.put("Sindi","sd");
		h.put("Siríaco","syr");
		h.put("Sogdiano","sog");
		h.put("Somali","so");
		h.put("Sorábio Alto","hsb");
		h.put("Sorábio Baixo","dsb");
		h.put("Suaíli","sw");
		h.put("Suazi","ss");
		h.put("Sueco","sv");
		h.put("Sumério","sux");
		h.put("Sundanês","su");
		h.put("Surinamês","srn");
		h.put("Tadjique","tg");
		h.put("Tagalo","tl");
		h.put("Tailandês","th");
		h.put("Taitiano","ty");
		h.put("Tâmil","ta");
		h.put("Tártaro","tt");
		h.put("Tártaro da Crimeia","crh");
		h.put("Tchuvache","cv");
		h.put("Télugo","te");
		h.put("Tétum","tet");
		h.put("Tibetano","bo");
		h.put("Tigré","tig");
		h.put("Tigrina","ti");
		h.put("Tlingit","tli");
		h.put("Tok Pisin","tpi");
		h.put("Tonganês","to");
		h.put("Toquelau","tkl");
		h.put("Truquês","chk");
		h.put("Tsonga","ts");
		h.put("Tswana","tn");
		h.put("Tumbuca","tum");
		h.put("Turco","tr");
		h.put("Turco Otomano","ota");
		h.put("Turcomeno","tk");
		h.put("Tuvaluano","tvl");
		h.put("Tuvano","tyv");
		h.put("Twi","tw");
		h.put("Ucraniano","uk");
		h.put("Ugarítico","uga");
		h.put("Uigure","ug");
		h.put("Umbundo","umb");
		h.put("Uolofe","wo");
		h.put("Urdu","ur");
		h.put("Uzbeque","uz");
		h.put("Valão","wa");
		h.put("Venda","ve");
		h.put("Vietnamita","vi");
		h.put("Volapuque","vo");
		h.put("Votíaco","udm");
		h.put("Voto","vot");
		h.put("Waray-Waray","war");
		h.put("Xhosa","xh");
		h.put("Yao","yao");
		h.put("Yapês","yap");
		h.put("Yi","ii");
		h.put("Zapoteca","zap");
		h.put("Zhuang","za");
		h.put("Zoncá","dz");
		h.put("Zulu","zu");
		h.put("Zuni","zun");
	}

	public static String threeLettersCode(String s) {
		return threeLettersCode(h, s);
	}
}
