package org.getalp.blexisma.plugins.semdictionary;

import org.cougaar.util.UnaryPredicate;
import org.getalp.blexisma.cougaarcom.ProxRequest;

/**
 * @author Alexandre Labadié
 * */
public class ProxRequestPredicate implements UnaryPredicate {

	/**
	 * Autogenerated serial version UID
	 */
	private static final long serialVersionUID = 7147736625913080709L;

	@Override
	public boolean execute(Object o) {
		ProxRequest p = null;
		if (o instanceof ProxRequest) {
			p = (ProxRequest)o;
			return !p.isEnd();
		}
		return false;
	}

}
