/**
 * 
 */
package org.getalp.dbnary.lit;

import java.util.HashMap;

import org.getalp.dbnary.LangTools;

/**
 * @author Mariam
 *
 */
public class LithuanianLangtoCode extends LangTools {
	static HashMap<String,String> h = new HashMap<String,String>();
	static {
	    h.put("Abchazų kalba", "ab");
	    h.put("Ačekų kalba", "ace");
	    h.put("Ačolių kalba", "ach");
	    h.put("Adygų kalba", "ady");
	    h.put("Afarų kalba", "aa");
	    h.put("Afrikanų kalba", "af");
	    h.put("Aimarų kalba", "ay");
	    h.put("Ainų kalba", "ain");
	    h.put("Airių kalba", "ga");
	    h.put("Akadų kalba", "akk");
	    h.put("Akanų kalba", "ak");
	    h.put("Albanų kalba", "sq");
	    h.put("Aleutų kalba", "ale");
	    h.put("Amharų kalba", "am");
	    h.put("Anglų kalba", "en");
	    h.put("Arabų kalba", "ar");
	    h.put("Aragoniečių kalba", "an");
	    h.put("Aramėjų kalba", "arc");
	    h.put("Arapahų kalba", "arp");
	    h.put("Armėnų kalba", "hy");
	    h.put("Arumunų kalba", "rup");
	    h.put("Asamų kalba", "as");
	    h.put("Astūrų kalba", "ast");
	    h.put("Aukštutinių sorbų kalba", "hsb");
	    h.put("Avadhių kalba", "awa");
	    h.put("Avarų kalba", "av");
	    h.put("Avestos kalba", "ae");
	    h.put("Azerbaidžaniečių kalba", "az");
	    h.put("Balių kalba", "ban");
	    h.put("Baltarusių kalba", "be");
	    h.put("Balubų kalba", "lua");
	    h.put("Bambarų kalba", "bm");
	    h.put("Baškirų kalba", "ba");
	    h.put("Baskų kalba", "eu");
	    h.put("Bedavijetų kalba", "bej");
	    h.put("Beludžių kalba", "bal");
	    h.put("Bembų kalba", "bem");
	    h.put("Bengalų kalba", "bn");
	    h.put("Bhodžpurių kalba", "bho");
	    h.put("Bislama kalba", "bi");
	    h.put("Bisų kalba", "bas");
	    h.put("Bosnių kalba", "bs");
	    h.put("Botijų kalba", "dz");
	    h.put("Bretonų kalba", "br");
	    h.put("Bugų kalba", "bug");
	    h.put("Bulgarų kalba", "bg");
	    h.put("Buriatų kalba", "bua");
	    h.put("Čagatajų kalba", "chg");
	    h.put("Čėčėnų kalba", "ce");
	    h.put("Čekų kalba", "cs");
	    h.put("Čemorų kalba", "ch");
	    h.put("Čerokių kalba", "chr");
	    h.put("Čibčių kalba", "chb");
	    h.put("Čičevų kalba", "ny");
	    h.put("Čigonų kalba", "rom");
	    h.put("Čijenų kalba", "chy");
	    h.put("Cimšių kalba", "tsi");
	    h.put("Činukų pidžino kalba", "chn");
	    h.put("Čiuvašų kalba", "cv");
	    h.put("Čoktavų kalba", "cho");
	    h.put("Dakotų kalba", "dak");
	    h.put("Dangmių kalba", "ada");
	    h.put("Danų kalba", "da");
	    h.put("Dargvų kalba", "dar");
	    h.put("Dinkų kalba", "din");
	    h.put("Dogribų kalba", "dgr");
	    h.put("Džao kalba", "yao");
	    h.put("Džuangų kalba", "za");
	    h.put("Džulų kalba", "dyu");
	    h.put("Efikų kalba", "efi");
	    h.put("Egiptiečių kalba", "egy");
	    h.put("Erzinų kalba", "myv");
	    h.put("Esperanto kalba", "eo");
	    h.put("Estų kalba", "et");
	    h.put("Evondų kalba", "ewo");
	    h.put("Evų kalba", "ee");
	    h.put("Fančių kalba", "fat");
	    h.put("Fangų (Pusiaujo Gvinėja) kalba", "fan");
	    h.put("Farerų kalba", "fo");
	    h.put("Fidžių kalba", "fj");
	    h.put("Filipinų kalba", "fil");
	    h.put("Finikiečių kalba", "phn");
	    h.put("Fryzų kalba", "fy");
	    h.put("Fulų kalba", "ff");
	    h.put("Furilų kalba", "fur");
	    h.put("Ga kalba", "gaa");
	    h.put("Gajų kalba", "gay");
	    h.put("Galisų kalba", "gl");
	    h.put("Gezo kalba", "gez");
	    h.put("Gondžių kalba", "gon");
	    h.put("Gotų kalba", "got");
	    h.put("Graikų kalba", "el");
	    h.put("Grenlandų kalba", "kl");
	    h.put("Gruzinų kalba", "ka");
	    h.put("Gudžaratų kalba", "gu");
	    h.put("Gvaranių kalba", "gn");
	    h.put("Haičio kreolų kalba", "ht");
	    h.put("Haidų kalba", "hai");
	    h.put("Hausų kalba", "ha");
	    h.put("Havajiečių kalba", "haw");
	    h.put("Hebrajų kalba", "he");
	    h.put("Hererų kalba", "hz");
	    h.put("Hindi kalba", "hi");
	    h.put("Hiri motu kalba", "ho");
	    h.put("Hititų kalba", "hit");
	    h.put("Hmongų kalba", "hmn");
	    h.put("Hupų kalba", "hup");
	    h.put("Ibanų kalba", "iba");
	    h.put("Ido kalba", "io");
	    h.put("Igbų kalba", "ig");
	    h.put("Ilokanų kalba", "ilo");
	    h.put("Ilongų kalba", "hil");
	    h.put("Inario samių kalba", "smn");
	    h.put("Indoneziečių kalba", "id");
	    h.put("Ingušų kalba", "inh");
	    h.put("Interlingua kalba", "ia");
	    h.put("Interlingue kalba", "ie");
	    h.put("Inuktituto kalba", "iu");
	    h.put("Inupiakų kalba", "ik");
	    h.put("Islandų kalba", "is");
	    h.put("Ispanų kalba", "es");
	    h.put("Italų kalba", "it");
	    h.put("Jakutų kalba", "sah");
	    h.put("Japesių kalba", "yap");
	    h.put("Japonų kalba", "ja");
	    h.put("Javiečių kalba", "jv");
	    h.put("Jidiš kalba", "yi");
	    h.put("Jorubų kalba", "yo");
	    h.put("Juodakojų kalba", "bla");
	    h.put("Kabardų kalba", "kbd");
	    h.put("Kabilų kalba", "kab");
	    h.put("Kačinų kalba", "kac");
	    h.put("Kadojų kalba", "cad");
	    h.put("Kalmukų kalba", "xal");
	    h.put("Kambų kalba", "kam");
	    h.put("Kanadų kalba", "kn");
	    h.put("Kanurų kalba", "kr");
	    h.put("Karačajų-balkarų kalba", "krc");
	    h.put("Karakalpakų kalba", "kaa");
	    h.put("Karelų kalba", "krl");
	    h.put("Karibų kalba", "car");
	    h.put("Kašmyrų kalba", "ks");
	    h.put("Kašubų kalba", "csb");
	    h.put("Katalonų kalba", "ca");
	    h.put("Kazachų kalba", "kk");
	    h.put("Kečujų kalba", "qu");
	    h.put("Khasių kalba", "kha");
	    h.put("Khmerų kalba", "km");
	    h.put("Khotaniečių kalba", "kho");
	    h.put("Kikujų kalba", "ki");
	    h.put("Kinjaruanda kalba", "rw");
	    h.put("Kinų kalba", "zh");
	    h.put("Kirgizų kalba", "ky");
	    h.put("Kiribačių kalba", "gil");
	    h.put("Kirundi kalba", "rn");
	    h.put("Komių kalba", "kv");
	    h.put("Kongiečių kalba", "kg");
	    h.put("Konkanų kalba", "kok");
	    h.put("Koptų kalba", "cop");
	    h.put("Korėjiečių kalba", "ko");
	    h.put("Kornų kalba", "kw");
	    h.put("Korsikiečių kalba", "co");
	    h.put("Kosrajų kalba", "kos");
	    h.put("Kosų kalba", "xh");
	    h.put("Kpelių kalba", "kpe");
	    h.put("Krijų kalba", "cr");
	    h.put("Krikų kalba", "mus");
	    h.put("Kroatų kalba", "hr");
	    h.put("Krymo totorių kalba", "crh");
	    h.put("Kučinų kalba", "gwi");
	    h.put("Kumikų kalba", "kum");
	    h.put("Kurdų kalba", "ku");
	    h.put("Kuruchų kalba", "kru");
	    h.put("Kvanjamų kalba", "kj");
	    h.put("Lambų kalba", "lam");
	    h.put("Laosiečių (lao) kalba", "lo");
	    h.put("Latvių kalba", "lv");
	    h.put("Lenkų kalba", "pl");
	    h.put("Lezgų kalba", "lez");
	    h.put("Lietuvių kalba", "lt");
	    h.put("Limburgiečių kalba", "li");
	    h.put("Lingala kalba", "ln");
	    h.put("Liuksemburgiečių kalba", "lb");
	    h.put("Lojban kalba", "jbo");
	    h.put("Lomongų kalba", "lol");
	    h.put("Lotynų kalba", "la");
	    h.put("Lozių kalba", "loz");
	    h.put("Lubų-katangų kalba", "lu");
	    h.put("Lugandų kalba", "lg");
	    h.put("Luo kalba", "luo");
	    h.put("Madurių kalba", "mad");
	    h.put("Makedonų kalba", "mk");
	    h.put("Malagasių kalba", "mg");
	    h.put("Malajalių kalba", "ml");
	    h.put("Malajų kalba", "ms");
	    h.put("Maldyvų kalba", "dv");
	    h.put("Maltiečių kalba", "mt");
	    h.put("Mandarų kalba", "mdr");
	    h.put("Mandžiūrų kalba", "mnc");
	    h.put("Manipurių kalba", "mni");
	    h.put("Maorių kalba", "mi");
	    h.put("Mapudunganų kalba", "arn");
	    h.put("Marathų kalba", "mr");
	    h.put("Marių kalba", "chm");
	    h.put("Maršaliečių kalba", "mh");
	    h.put("Marvarių kalba", "mwr");
	    h.put("Masajų kalba", "mas");
	    h.put("Mbundų kalba", "kmb");
	    h.put("Mendejų kalba", "men");
	    h.put("Menksiečių kalba", "gv");
	    h.put("Mikmakų kalba", "mic");
	    h.put("Minangkabau kalba", "min");
	    h.put("Mirandų kalba", "mwl");
	    h.put("Mizų kalba", "lus");
	    h.put("Mjanmų kalba", "my");
	    h.put("Mohaukų kalba", "moh");
	    h.put("Mokšų kalba", "mdf");
	    h.put("Moldavų kalba", "mo");
	    h.put("Mongolų kalba", "mn");
	    h.put("Moorių kalba", "mos");
	    h.put("Naujoji norvegų kalba", "nn");
	    h.put("Nauriečių kalba", "na");
	    h.put("Navahų kalba", "nv");
	    h.put("Ndongų kalba", "ng");
	    h.put("Neapoliečių kalba", "nap");
	    h.put("Nepalų kalba", "ne");
	    h.put("Nevarų kalba", "new");
	    h.put("Niamvezių kalba", "nym");
	    h.put("Niankorių kalba", "nyn");
	    h.put("Niasų kalba", "nia");
	    h.put("Niorų kalba", "nyo");
	    h.put("Niue kalba", "niu");
	    h.put("Nogajų kalba", "nog");
	    h.put("Norvegų bukmolų kalba", "nb");
	    h.put("Norvegų kalba", "no");
	    h.put("Nuosu kalba", "ii");
	    h.put("Nzemų kalba", "nzi");
	    h.put("Odžibvės kalba", "oj");
	    h.put("Oksitanų kalba", "oc");
	    h.put("Olandų kalba", "nl");
	    h.put("Orijų kalba", "or");
	    h.put("Oromų kalba", "om");
	    h.put("Osetinų kalba", "os");
	    h.put("Osmanų turkų kalba", "ota");
	    h.put("Palauiečių kalba", "pau");
	    h.put("Pali kalba", "pi");
	    h.put("Pampangų kalba", "pam");
	    h.put("Pangasinų kalba", "pag");
	    h.put("Papiamento kalba", "pap");
	    h.put("Papua pidžinų kalba", "tpi");
	    h.put("Pendžabų kalba", "pa");
	    h.put("Persų kalba", "fa");
	    h.put("Pietų Altajaus kalba", "alt");
	    h.put("Pietų ndebelių kalba", "nr");
	    h.put("Pietų sotų kalba", "st");
	    h.put("Ponapės kalba", "pon");
	    h.put("Portugalų kalba", "pt");
	    h.put("Prancūzų kalba", "fr");
	    h.put("Puštūnų kalba", "ps");
	    h.put("Rapanujų kalba", "rap");
	    h.put("Rarotongų kalba", "rar");
	    h.put("Retoromanų kalba", "rm");
	    h.put("Rumunų kalba", "ro");
	    h.put("Rusų kalba", "ru");
	    h.put("Šablonas:lang:afh", "afh");
	    h.put("Šablonas:lang:anp", "anp");
	    h.put("Šablonas:lang:arw", "arw");
	    h.put("Šablonas:lang:bik", "bik");
	    h.put("Šablonas:lang:bin", "bin");
	    h.put("Šablonas:lang:bra", "bra");
	    h.put("Šablonas:lang:byn", "byn");
	    h.put("Šablonas:lang:chp", "chp");
	    h.put("Šablonas:lang:del", "del");
	    h.put("Šablonas:lang:den", "den");
	    h.put("Šablonas:lang:doi", "doi");
	    h.put("Šablonas:lang:dua", "dua");
	    h.put("Šablonas:lang:eka", "eka");
	    h.put("Šablonas:lang:elx", "elx");
	    h.put("Šablonas:lang:fon", "fon");
	    h.put("Šablonas:lang:frs", "frs");
	    h.put("Šablonas:lang:gba", "gba");
	    h.put("Šablonas:lang:gor", "gor");
	    h.put("Šablonas:lang:grb", "grb");
	    h.put("Šablonas:lang:jpr", "jpr");
	    h.put("Šablonas:lang:jrb", "jrb");
	    h.put("Šablonas:lang:kaw", "kaw");
	    h.put("Šablonas:lang:kut", "kut");
	    h.put("Šablonas:lang:lah", "lah");
	    h.put("Šablonas:lang:lui", "lui");
	    h.put("Šablonas:lang:lun", "lun");
	    h.put("Šablonas:lang:mag", "mag");
	    h.put("Šablonas:lang:mai", "mai");
	    h.put("Šablonas:lang:mak", "mak");
	    h.put("Šablonas:lang:man", "man");
	    h.put("Šablonas:lang:mis", "mis");
	    h.put("Šablonas:lang:mul", "mul");
	    h.put("Šablonas:lang:nqo", "nqo");
	    h.put("Šablonas:lang:nwc", "nwc");
	    h.put("Šablonas:lang:osa", "osa");
	    h.put("Šablonas:lang:raj", "raj");
	    h.put("Šablonas:lang:sam", "sam");
	    h.put("Šablonas:lang:sma", "sma");
	    h.put("Šablonas:lang:smj", "smj");
	    h.put("Šablonas:lang:sog", "sog");
	    h.put("Šablonas:lang:syc", "syc");
	    h.put("Šablonas:lang:syr", "syr");
	    h.put("Šablonas:lang:tem", "tem");
	    h.put("Šablonas:lang:ter", "ter");
	    h.put("Šablonas:lang:tlh", "tlh");
	    h.put("Šablonas:lang:tmh", "tmh");
	    h.put("Šablonas:lang:und", "und");
	    h.put("Šablonas:lang:was", "was");
	    h.put("Šablonas:lang:zap", "zap");
	    h.put("Šablonas:lang:zbl", "zbl");
	    h.put("Šablonas:lang:zxx", "zxx");
	    h.put("Samojiečių kalba", "sm");
	    h.put("Sandavių kalba", "sad");
	    h.put("Sanskrito kalba", "sa");
	    h.put("Santalų kalba", "sat");
	    h.put("Šanų kalba", "shn");
	    h.put("Sardiniečių kalba", "sc");
	    h.put("Sasakų kalba", "sas");
	    h.put("Sebuanų kalba", "ceb");
	    h.put("Sefardžių kalba", "lad");
	    h.put("Selkupų kalba", "sel");
	    h.put("Senoji airių kalba", "sga");
	    h.put("Senoji anglų kalba", "ang");
	    h.put("Senoji aukštutinių vokiečių kalba", "goh");
	    h.put("Senoji bažnytinė slavų kalba", "cu");
	    h.put("Senoji persų kalba", "peo");
	    h.put("Senoji prancūzų kalba", "fro");
	    h.put("Senoji provansalų kalba", "pro");
	    h.put("Senovės graikų kalba", "grc");
	    h.put("Senovės skandinavų kalba", "non");
	    h.put("Serbų kalba", "sr");
	    h.put("Serbų-kroatų kalba", "sh");
	    h.put("Serersinų kalba", "srr");
	    h.put("Šiaurės fryzų kalba", "frr");
	    h.put("Šiaurės ndebelių kalba", "nd");
	    h.put("Šiaurės samių kalba", "se");
	    h.put("Šiaurės Soto kalba", "nso");
	    h.put("Siciliečių kalba", "scn");
	    h.put("Sidamų kalba", "sid");
	    h.put("Sindhų kalba", "sd");
	    h.put("Sinhalų kalba", "si");
	    h.put("Skolto samių kalba", "sms");
	    h.put("Škotų gėlų kalba", "gd");
	    h.put("Škotų kalba", "sco");
	    h.put("Slovakų kalba", "sk");
	    h.put("Slovėnų kalba", "sl");
	    h.put("Somalių kalba", "so");
	    h.put("Songo kalba", "sg");
	    h.put("Soninkių kalba", "snk");
	    h.put("Šonų kalba", "sn");
	    h.put("Sukumų kalba", "suk");
	    h.put("Šumerų kalba", "sux");
	    h.put("Sundų kalba", "su");
	    h.put("Suomių kalba", "fi");
	    h.put("Surinamiečių kalba", "srn");
	    h.put("Susu kalba", "sus");
	    h.put("Svahilių kalba", "sw");
	    h.put("Svazių kalba", "ss");
	    h.put("Švedų kalba", "sv");
	    h.put("Šveicarijos vokiečių kalba", "gsw");
	    h.put("Tadžikų kalba", "tg");
	    h.put("Tagalų kalba", "tl");
	    h.put("Taitiečių kalba", "ty");
	    h.put("Tajų kalba", "th");
	    h.put("Tamilų kalba", "ta");
	    h.put("Telugų kalba", "te");
	    h.put("Tetunų kalba", "tet");
	    h.put("Tibetiečių kalba", "bo");
	    h.put("Tigrinų kalba", "ti");
	    h.put("Tigrių kalba", "tig");
	    h.put("Tivų kalba", "tiv");
	    h.put("Tlingitų kalba", "tli");
	    h.put("Tokelauiečių kalba", "tkl");
	    h.put("Tongų (Malavis) kalba", "tog");
	    h.put("Tongų (Tonga) kalba", "to");
	    h.put("Totorių kalba", "tt");
	    h.put("Trukų kalba", "chk");
	    h.put("Tsongų kalba", "ts");
	    h.put("Tsvanų kalba", "tn");
	    h.put("Tumbukų kalba", "tum");
	    h.put("Turkmėnų kalba", "tk");
	    h.put("Turkų kalba", "tr");
	    h.put("Tuvalų kalba", "tvl");
	    h.put("Tuvių kalba", "tyv");
	    h.put("Tvi kalba", "tw");
	    h.put("Udmurtų kalba", "udm");
	    h.put("Ugaritų kalba", "uga");
	    h.put("Uigūrų kalba", "ug");
	    h.put("Ukrainiečių kalba", "uk");
	    h.put("Umbundu kalba", "umb");
	    h.put("Urdų kalba", "ur");
	    h.put("Uzbekų kalba", "uz");
	    h.put("Vajų kalba", "vai");
	    h.put("Valonų kalba", "wa");
	    h.put("Valų kalba", "cy");
	    h.put("Varajų kalba", "war");
	    h.put("Vendų kalba", "ve");
	    h.put("Vengrų kalba", "hu");
	    h.put("Vidurinioji airių kalba", "mga");
	    h.put("Vidurinioji anglų kalba", "enm");
	    h.put("Vidurinioji aukštutinių vokiečių kalba", "gmh");
	    h.put("Vidurinioji olandų kalba", "dum");
	    h.put("Vidurinioji persų kalba", "pal");
	    h.put("Vidurinioji prancūzų kalba", "frm");
	    h.put("Vietnamiečių kalba", "vi");
	    h.put("Vodų kalba", "vot");
	    h.put("Vokiečių kalba", "de");
	    h.put("Volaitų kalba", "wal");
	    h.put("Volapiuko kalba", "vo");
	    h.put("Volofų kalba", "wo");
	    h.put("Zazų kalba", "zza");
	    h.put("Žemutinių saksonų kalba", "nds");
	    h.put("Žemutinių sorbų kalba", "dsb");
	    h.put("Zenagų kalba", "zen");
	    h.put("Zulų kalba", "zu");
	    h.put("Zunių kalba", "zun");
	}

	public static String threeLettersCode(String s) {
		return threeLettersCode(h, s);
	}

}
