/**
 * 
 */
package org.getalp.dbnary.bul;

import org.getalp.dbnary.LangTools;

import java.util.HashMap;

/**
 * @author Andon
 *
 */
public class BulgarianLangtoCode extends LangTools {
	static HashMap<String,String> h = new HashMap<String,String>();
	
	static {
        h.put("Шаблон:aa", "aa");
        h.put("Шаблон:ab", "ab");
        h.put("африкаанс", "af");
        h.put("Шаблон:ak", "ak");
        h.put("албански", "sq");
        h.put("Шаблон:am", "am");
        h.put("арабски", "ar");
        h.put("Шаблон:an", "an");
        h.put("арменски", "hy");
        h.put("Шаблон:as", "as");
        h.put("Шаблон:av", "av");
        h.put("Шаблон:ae", "ae");
        h.put("Шаблон:ay", "ay");
        h.put("азербейджански", "az");
        h.put("Шаблон:ba", "ba");
        h.put("Шаблон:bm", "bm");
        h.put("баски", "eu");
        h.put("белоруски", "be");
        h.put("Шаблон:bn", "bn");
        h.put("Шаблон:bh", "bh");
        h.put("Шаблон:bi", "bi");
        h.put("Шаблон:bo", "bo");
        h.put("Шаблон:bs", "bs");
        h.put("бретонски", "br");
        h.put("български", "bg");
        h.put("Шаблон:my", "my");
        h.put("каталонски", "ca");
        h.put("чешки", "cs");
        h.put("Шаблон:ch", "ch");
        h.put("Шаблон:ce", "ce");
        h.put("китайски", "zh");
        h.put("Шаблон:cu", "cu");
        h.put("Шаблон:cv", "cv");
        h.put("корнийски", "kw");
        h.put("Шаблон:co", "co");
        h.put("криа", "cr");
        h.put("уелски", "cy");
        h.put("чешки", "cs");
        h.put("датски", "da");
        h.put("немски", "de");
        h.put("Шаблон:dv", "dv");
        h.put("холандски", "nl");
        h.put("Шаблон:dz", "dz");
        h.put("гръцки", "el");
        h.put("английски", "en");
        h.put("есперанто", "eo");
        h.put("естонски", "et");
        h.put("баски", "eu");
        h.put("Шаблон:ee", "ee");
        h.put("Шаблон:fo", "fo");
        h.put("персийски", "fa");
        h.put("Шаблон:fj", "fj");
        h.put("фински", "fi");
        h.put("френски", "fr");
        h.put("френски", "fr");
        h.put("фрисийски", "fy");
        h.put("Шаблон:ff", "ff");
        h.put("грузински", "ka");
        h.put("немски", "de");
        h.put("Шаблон:gd", "gd");
        h.put("ирландски", "ga");
        h.put("Шаблон:gl", "gl");
        h.put("Manx Gaelic", "gv");
        h.put("гръцки", "el");
        h.put("Шаблон:gn", "gn");
        h.put("Шаблон:gu", "gu");
        h.put("Шаблон:ht", "ht");
        h.put("Шаблон:ha", "ha");
        h.put("иврит", "he");
        h.put("Шаблон:hz", "hz");
        h.put("хинди", "hi");
        h.put("Шаблон:ho", "ho");
        h.put("хърватски", "hr");
        h.put("унгарски", "hu");
        h.put("арменски", "hy");
        h.put("Шаблон:ig", "ig");
        h.put("исландски", "is");
        h.put("Шаблон:io", "io");
        h.put("Шаблон:ii", "ii");
        h.put("Шаблон:iu", "iu");
        h.put("Шаблон:ie", "ie");
        h.put("Шаблон:ia", "ia");
        h.put("индонезийски", "id");
        h.put("Шаблон:ik", "ik");
        h.put("исландски", "is");
        h.put("италиански", "it");
        h.put("Шаблон:jv", "jv");
        h.put("японски", "ja");
        h.put("Шаблон:kl", "kl");
        h.put("Шаблон:kn", "kn");
        h.put("Шаблон:ks", "ks");
        h.put("грузински", "ka");
        h.put("Шаблон:kr", "kr");
        h.put("Шаблон:kk", "kk");
        h.put("Шаблон:km", "km");
        h.put("Шаблон:ki", "ki");
        h.put("Шаблон:rw", "rw");
        h.put("Шаблон:ky", "ky");
        h.put("Шаблон:kv", "kv");
        h.put("Шаблон:kg", "kg");
        h.put("корейски", "ko");
        h.put("Шаблон:kj", "kj");
        h.put("Шаблон:ku", "ku");
        h.put("Шаблон:lo", "lo");
        h.put("латински", "la");
        h.put("латвийски", "lv");
        h.put("Шаблон:li", "li");
        h.put("Шаблон:ln", "ln");
        h.put("литовски", "lt");
        h.put("люксембургски", "lb");
        h.put("Шаблон:lu", "lu");
        h.put("Шаблон:lg", "lg");
        h.put("македонски", "mk");
        h.put("Шаблон:mh", "mh");
        h.put("Шаблон:ml", "ml");
        h.put("маори", "mi");
        h.put("махаращрийски", "mr");
        h.put("малайски", "ms");
        h.put("македонски", "mk");
        h.put("Шаблон:mg", "mg");
        h.put("Шаблон:mt", "mt");
        h.put("Шаблон:mn", "mn");
        h.put("маори", "mi");
        h.put("малайски", "ms");
        h.put("Шаблон:my", "my");
        h.put("Шаблон:na", "na");
        h.put("Шаблон:nv", "nv");
        h.put("Шаблон:nr", "nr");
        h.put("Шаблон:nd", "nd");
        h.put("Шаблон:ng", "ng");
        h.put("Шаблон:ne", "ne");
        h.put("холандски", "nl");
        h.put("Шаблон:nn", "nn");
        h.put("Шаблон:nb", "nb");
        h.put("норвежки", "no");
        h.put("Шаблон:ny", "ny");
        h.put("Шаблон:oc", "oc");
        h.put("Шаблон:oj", "oj");
        h.put("Шаблон:or", "or");
        h.put("Шаблон:om", "om");
        h.put("Шаблон:os", "os");
        h.put("Шаблон:pa", "pa");
        h.put("персийски", "fa");
        h.put("Шаблон:pi", "pi");
        h.put("полски", "pl");
        h.put("португалски", "pt");
        h.put("Шаблон:ps", "ps");
        h.put("Шаблон:qu", "qu");
        h.put("Шаблон:rm", "rm");
        h.put("румънски", "ro");
        h.put("румънски", "ro");
        h.put("Шаблон:rn", "rn");
        h.put("руски", "ru");
        h.put("Шаблон:sg", "sg");
        h.put("Шаблон:sa", "sa");
        h.put("сингалски", "si");
        h.put("словашки", "sk");
        h.put("словашки", "sk");
        h.put("словенски", "sl");
        h.put("Шаблон:se", "se");
        h.put("самоански", "sm");
        h.put("Шаблон:sn", "sn");
        h.put("Шаблон:sd", "sd");
        h.put("Шаблон:so", "so");
        h.put("Шаблон:st", "st");
        h.put("испански", "es");
        h.put("албански", "sq");
        h.put("Шаблон:sc", "sc");
        h.put("сръбски", "sr");
        h.put("Шаблон:ss", "ss");
        h.put("Шаблон:su", "su");
        h.put("Шаблон:sw", "sw");
        h.put("шведски", "sv");
        h.put("Шаблон:ty", "ty");
        h.put("тамилски", "ta");
        h.put("Шаблон:tt", "tt");
        h.put("Шаблон:te", "te");
        h.put("Шаблон:tg", "tg");
        h.put("тагалог", "tl");
        h.put("тайландски", "th");
        h.put("Шаблон:bo", "bo");
        h.put("Шаблон:ti", "ti");
        h.put("Шаблон:to", "to");
        h.put("Шаблон:tn", "tn");
        h.put("Шаблон:ts", "ts");
        h.put("Шаблон:tk", "tk");
        h.put("турски", "tr");
        h.put("Шаблон:tw", "tw");
        h.put("Шаблон:ug", "ug");
        h.put("украински", "uk");
        h.put("урду", "ur");
        h.put("Шаблон:uz", "uz");
        h.put("Шаблон:ve", "ve");
        h.put("виетнамски", "vi");
        h.put("Шаблон:vo", "vo");
        h.put("уелски", "cy");
        h.put("Шаблон:wa", "wa");
        h.put("Шаблон:wo", "wo");
        h.put("Шаблон:xh", "xh");
        h.put("Шаблон:yi", "yi");
        h.put("йоруба", "yo");
        h.put("Шаблон:za", "za");
        h.put("китайски", "zh");
        h.put("Шаблон:zu", "zu");

        // Do not delete, alternate forms and missing forms in Bulgarian templates.
        h.put("интерлингва", "ina");
        h.put("баварски", "bar");
        h.put("азерски", "az");
        h.put("азърски", "az");
        h.put("рапануи", "rap");
        h.put("хавайски", "haw");
        h.put("шотландски", "gd");
        h.put("кюрдски", "ku");
        h.put("нидерландски", "nl");
        h.put("финландски", "fi");
        h.put("русский", "ru");
        h.put("хаитянски креолски", "hat");
        h.put("жемайтийски", "sgs");
        h.put("кримскотатарски", "crh");
        h.put("науатъл", "nci");
        h.put("нахуатъл", "nci");
        h.put("каталански", "ca");
        h.put("каталан", "ca");
        h.put("хъватски", "hrv");
        h.put("крия", "cr");
        h.put("филипински", "fil");
        h.put("беларуски", "be");
        h.put("санскрит", "sa");
        h.put("идо", "io");
        h.put("осетински", "os");
        h.put("старобългарски", "cu");


	}

	public static String threeLettersCode(String s) {
		return threeLettersCode(h, s);
	}

}
