/**
 * 
 */
package org.getalp.dbnary.tur;

import java.util.HashMap;

import org.getalp.dbnary.LangTools;

/**
 * @author Mariam
 *
 */
public class TurkishLangtoCode extends LangTools {
	static HashMap<String,String> h = new HashMap<String,String>();
	static {
	    h.put("Abhazca", "ab");
	    h.put("Adigece", "ady");
	    h.put("Afar", "aa");
	    h.put("Afrikanca", "af");
	    h.put("Akan dili", "ak");
	    h.put("Akatça", "akk");
	    h.put("Almanca", "de");
	    h.put("Altayca", "alt");
	    h.put("Amharca", "am");
	    h.put("Aragonca", "an");
	    h.put("Aramice", "arc");
	    h.put("Arapça", "ar");
	    h.put("Aravak", "arw");
	    h.put("Arnavutça", "sq");
	    h.put("Aşağı Almanca", "nds");
	    h.put("Assam dili", "as");
	    h.put("Asturca", "ast");
	    h.put("Avarca", "av");
	    h.put("Aymaraca", "ay");
	    h.put("Azerice", "az");
	    h.put("Balinezce", "ban");
	    h.put("Bambara", "bm");
	    h.put("Baskça", "eu");
	    h.put("Başkurtça", "ba");
	    h.put("Beluçi", "bal");
	    h.put("Bemba (Sambia)", "bem");
	    h.put("Bengalce", "bn");
	    h.put("Beyaz Rusça", "be");
	    h.put("Birmanca", "my");
	    h.put("Bislama", "bi");
	    h.put("Bokmål", "nb");
	    h.put("Boşnakça", "bs");
	    h.put("Bretonca", "br");
	    h.put("Buginezce", "bug");
	    h.put("Bulgarca", "bg");
	    h.put("Buryatça", "bua");
	    h.put("Butanca", "dz");
	    h.put("Çağatayca", "chg");
	    h.put("Cavaca", "jv");
	    h.put("Cebuano", "ceb");
	    h.put("Çeçence", "ce");
	    h.put("Çekçe", "cs");
	    h.put("Çeyence", "chy");
	    h.put("Chamorro", "ch");
	    h.put("Cherokee", "chr");
	    h.put("Chichewa", "ny");
	    h.put("Choctaw", "cho");
	    h.put("Çince", "zh");
	    h.put("Çuvaşça", "cv");
	    h.put("Danca", "da");
	    h.put("Endonezce", "id");
	    h.put("Ermenice", "hy");
	    h.put("Ersya", "myv");
	    h.put("Eski İngilizce", "ang");
	    h.put("Eski Nortça", "non");
	    h.put("Eski Slavca", "cu");
	    h.put("Eski Yüksek Almanca", "goh");
	    h.put("Eski Yunanca", "grc");
	    h.put("Esperanto", "eo");
	    h.put("Estonca", "et");
	    h.put("Ewe", "ee");
	    h.put("Faroe dili", "fo");
	    h.put("Farsça", "fa");
	    h.put("Fiji", "fj");
	    h.put("Fince", "fi");
	    h.put("Fransızca", "fr");
	    h.put("Friulian", "fur");
	    h.put("Frizce", "fy");
	    h.put("Fula dili", "ff");
	    h.put("Galce", "cy");
	    h.put("Galiçyaca", "gl");
	    h.put("Gayo", "gay");
	    h.put("Gotça", "got");
	    h.put("Grönlandca", "kl");
	    h.put("Guarani", "gn");
	    h.put("Gucaratça", "gu");
	    h.put("Gürcüce", "ka");
	    h.put("Haitice", "ht");
	    h.put("Hausa", "ha");
	    h.put("Hawaii dili", "haw");
	    h.put("Herero", "hz");
	    h.put("Hintçe", "hi");
	    h.put("Hiri Motu", "ho");
	    h.put("Hırvatça", "hr");
	    h.put("Hollandaca", "nl");
	    h.put("İban", "iba");
	    h.put("İbranice", "he");
	    h.put("İdo", "io");
	    h.put("İgbo", "ig");
	    h.put("Ilokano", "ilo");
	    h.put("İngilizce", "en");
	    h.put("Inguzca", "inh");
	    h.put("Interlingua", "ie");
	    h.put("İnterlingua", "ia");
	    h.put("Inuktitut", "iu");
	    h.put("Inupiak", "ik");
	    h.put("İrlandaca", "ga");
	    h.put("İskoç İngilizcesi", "sco");
	    h.put("İskoçça", "gd");
	    h.put("İspanyolca", "es");
	    h.put("İsveççe", "sv");
	    h.put("İsviçre Almancası", "gsw");
	    h.put("İtalyanca", "it");
	    h.put("İzlandaca", "is");
	    h.put("Japonca", "ja");
	    h.put("Kabarca", "kbd");
	    h.put("Kalmukça", "xal");
	    h.put("Kanarece", "kn");
	    h.put("Kanuri dili", "kr");
	    h.put("Kapampangan", "pam");
	    h.put("Karaayakça", "bla");
	    h.put("Karaçay Balkarca", "krc");
	    h.put("Karakalpakça", "kaa");
	    h.put("Karelce", "krl");
	    h.put("Kaşupça", "csb");
	    h.put("Katalanca", "ca");
	    h.put("Kawi", "kaw");
	    h.put("Kazakça", "kk");
	    h.put("Keçua", "qu");
	    h.put("Kernevekçe", "kw");
	    h.put("Keşmirce", "ks");
	    h.put("Kikuyu", "ki");
	    h.put("Kiribati", "gil");
	    h.put("Kirundi", "rn");
	    h.put("Kırgızca", "ky");
	    h.put("Kırım Tatarca", "crh");
	    h.put("Klingonca", "tlh");
	    h.put("Kmer", "km");
	    h.put("Komi", "kv");
	    h.put("Kongo dili", "kg");
	    h.put("Konkani", "kok");
	    h.put("Korece", "ko");
	    h.put("Korsikaca", "co");
	    h.put("Kosrae", "kos");
	    h.put("Kri", "cr");
	    h.put("Kuanyama", "kj");
	    h.put("Kumukça", "kum");
	    h.put("Kürtçe", "ku");
	    h.put("Laotça", "lo");
	    h.put("Latince", "la");
	    h.put("Lehçe", "pl");
	    h.put("Letonca", "lv");
	    h.put("Limburgca", "li");
	    h.put("Lingala", "ln");
	    h.put("Litvanca", "lt");
	    h.put("Lojban", "jbo");
	    h.put("Luganda", "lg");
	    h.put("Lüksemburgça", "lb");
	    h.put("Maasai", "mas");
	    h.put("Macarca", "hu");
	    h.put("Madurezce", "mad");
	    h.put("Makassar", "mak");
	    h.put("Makedonca", "mk");
	    h.put("Malayalam", "ml");
	    h.put("Malayca", "ms");
	    h.put("Maledivce", "dv");
	    h.put("Malgaşça", "mg");
	    h.put("Maltaca", "mt");
	    h.put("Manksça", "gv");
	    h.put("Maori", "mi");
	    h.put("Mapudungun", "arn");
	    h.put("Marathi dili", "mr");
	    h.put("Mari", "chm");
	    h.put("Marşalca", "mh");
	    h.put("Mikmakça", "mic");
	    h.put("Minangkabau", "min");
	    h.put("Mısırca", "egy");
	    h.put("Moğolca", "mn");
	    h.put("Mohawk", "moh");
	    h.put("Mokşa", "mdf");
	    h.put("Moldovca", "mo");
	    h.put("Muskogee", "mus");
	    h.put("Napolice", "nap");
	    h.put("Nauruca", "na");
	    h.put("Navayo", "nv");
	    h.put("Ndebele", "nd");
	    h.put("Ndebele dili", "nr");
	    h.put("Ndonga", "ng");
	    h.put("Nepal Bhasa dili", "new");
	    h.put("Nepalce", "ne");
	    h.put("Nogayca", "nog");
	    h.put("Norveççe", "no");
	    h.put("Ojibwe", "oj");
	    h.put("Oksitanca", "oc");
	    h.put("Oriya", "or");
	    h.put("Oromo", "om");
	    h.put("Osetçe", "os");
	    h.put("Osmanlıca", "ota");
	    h.put("Özbekçe", "uz");
	    h.put("Pali", "pi");
	    h.put("Papiamentu", "pap");
	    h.put("Pedi", "nso");
	    h.put("Pencapça", "pa");
	    h.put("Peştun", "ps");
	    h.put("Portekizce", "pt");
	    h.put("Rapanui", "rap");
	    h.put("Reto Romanca", "rm");
	    h.put("Rumence", "ro");
	    h.put("Rusça", "ru");
	    h.put("Rwandi", "rw");
	    h.put("Şablon:ace", "ace");
	    h.put("Şablon:ach", "ach");
	    h.put("Şablon:ada", "ada");
	    h.put("Şablon:ae", "ae");
	    h.put("Şablon:afh", "afh");
	    h.put("Şablon:ain", "ain");
	    h.put("Şablon:ale", "ale");
	    h.put("Şablon:anp", "anp");
	    h.put("Şablon:arp", "arp");
	    h.put("Şablon:awa", "awa");
	    h.put("Şablon:bas", "bas");
	    h.put("Şablon:bej", "bej");
	    h.put("Şablon:bho", "bho");
	    h.put("Şablon:bik", "bik");
	    h.put("Şablon:bin", "bin");
	    h.put("Şablon:bra", "bra");
	    h.put("Şablon:byn", "byn");
	    h.put("Şablon:cad", "cad");
	    h.put("Şablon:car", "car");
	    h.put("Şablon:chb", "chb");
	    h.put("Şablon:chk", "chk");
	    h.put("Şablon:chn", "chn");
	    h.put("Şablon:chp", "chp");
	    h.put("Şablon:cop", "cop");
	    h.put("Şablon:dak", "dak");
	    h.put("Şablon:dar", "dar");
	    h.put("Şablon:del", "del");
	    h.put("Şablon:den", "den");
	    h.put("Şablon:dgr", "dgr");
	    h.put("Şablon:din", "din");
	    h.put("Şablon:doi", "doi");
	    h.put("Şablon:dua", "dua");
	    h.put("Şablon:dum", "dum");
	    h.put("Şablon:dyu", "dyu");
	    h.put("Şablon:efi", "efi");
	    h.put("Şablon:eka", "eka");
	    h.put("Şablon:elx", "elx");
	    h.put("Şablon:enm", "enm");
	    h.put("Şablon:ewo", "ewo");
	    h.put("Şablon:fan", "fan");
	    h.put("Şablon:fat", "fat");
	    h.put("Şablon:fil", "fil");
	    h.put("Şablon:fon", "fon");
	    h.put("Şablon:frm", "frm");
	    h.put("Şablon:fro", "fro");
	    h.put("Şablon:frr", "frr");
	    h.put("Şablon:frs", "frs");
	    h.put("Şablon:gaa", "gaa");
	    h.put("Şablon:gba", "gba");
	    h.put("Şablon:gez", "gez");
	    h.put("Şablon:gmh", "gmh");
	    h.put("Şablon:gon", "gon");
	    h.put("Şablon:gor", "gor");
	    h.put("Şablon:grb", "grb");
	    h.put("Şablon:gwi", "gwi");
	    h.put("Şablon:hai", "hai");
	    h.put("Şablon:hil", "hil");
	    h.put("Şablon:hit", "hit");
	    h.put("Şablon:hmn", "hmn");
	    h.put("Şablon:hup", "hup");
	    h.put("Şablon:jpr", "jpr");
	    h.put("Şablon:jrb", "jrb");
	    h.put("Şablon:kab", "kab");
	    h.put("Şablon:kac", "kac");
	    h.put("Şablon:kam", "kam");
	    h.put("Şablon:kha", "kha");
	    h.put("Şablon:kho", "kho");
	    h.put("Şablon:kmb", "kmb");
	    h.put("Şablon:kpe", "kpe");
	    h.put("Şablon:kru", "kru");
	    h.put("Şablon:kut", "kut");
	    h.put("Şablon:lah", "lah");
	    h.put("Şablon:lam", "lam");
	    h.put("Şablon:lez", "lez");
	    h.put("Şablon:lol", "lol");
	    h.put("Şablon:loz", "loz");
	    h.put("Şablon:lu", "lu");
	    h.put("Şablon:lua", "lua");
	    h.put("Şablon:lui", "lui");
	    h.put("Şablon:lun", "lun");
	    h.put("Şablon:luo", "luo");
	    h.put("Şablon:lus", "lus");
	    h.put("Şablon:mag", "mag");
	    h.put("Şablon:mai", "mai");
	    h.put("Şablon:man", "man");
	    h.put("Şablon:mdr", "mdr");
	    h.put("Şablon:men", "men");
	    h.put("Şablon:mga", "mga");
	    h.put("Şablon:mis", "mis");
	    h.put("Şablon:mnc", "mnc");
	    h.put("Şablon:mni", "mni");
	    h.put("Şablon:mos", "mos");
	    h.put("Şablon:mul", "mul");
	    h.put("Şablon:mwl", "mwl");
	    h.put("Şablon:mwr", "mwr");
	    h.put("Şablon:nia", "nia");
	    h.put("Şablon:niu", "niu");
	    h.put("Şablon:nqo", "nqo");
	    h.put("Şablon:nwc", "nwc");
	    h.put("Şablon:nym", "nym");
	    h.put("Şablon:nyn", "nyn");
	    h.put("Şablon:nyo", "nyo");
	    h.put("Şablon:nzi", "nzi");
	    h.put("Şablon:osa", "osa");
	    h.put("Şablon:pag", "pag");
	    h.put("Şablon:pal", "pal");
	    h.put("Şablon:pau", "pau");
	    h.put("Şablon:peo", "peo");
	    h.put("Şablon:phn", "phn");
	    h.put("Şablon:pon", "pon");
	    h.put("Şablon:pro", "pro");
	    h.put("Şablon:raj", "raj");
	    h.put("Şablon:rar", "rar");
	    h.put("Şablon:rom", "rom");
	    h.put("Şablon:rup", "rup");
	    h.put("Şablon:sad ", "sad");
	    h.put("Şablon:sam", "sam");
	    h.put("Şablon:sas", "sas");
	    h.put("Şablon:sat", "sat");
	    h.put("Şablon:sel", "sel");
	    h.put("Şablon:sga", "sga");
	    h.put("Şablon:shn", "shn");
	    h.put("Şablon:sid", "sid");
	    h.put("Şablon:sma", "sma");
	    h.put("Şablon:smj", "smj");
	    h.put("Şablon:sms", "sms");
	    h.put("Şablon:snk", "snk");
	    h.put("Şablon:sog", "sog");
	    h.put("Şablon:srn", "srn");
	    h.put("Şablon:srr", "srr");
	    h.put("Şablon:suk", "suk");
	    h.put("Şablon:sus", "sus");
	    h.put("Şablon:syc", "syc");
	    h.put("Şablon:tem", "tem");
	    h.put("Şablon:ter", "ter");
	    h.put("Şablon:tig", "tig");
	    h.put("Şablon:tiv", "tiv");
	    h.put("Şablon:tkl", "tkl");
	    h.put("Şablon:tli", "tli");
	    h.put("Şablon:tmh", "tmh");
	    h.put("Şablon:tog", "tog");
	    h.put("Şablon:tsi", "tsi");
	    h.put("Şablon:uga", "uga");
	    h.put("Şablon:umb", "umb");
	    h.put("Şablon:und", "und");
	    h.put("Şablon:vai", "vai");
	    h.put("Şablon:wal", "wal");
	    h.put("Şablon:was", "was");
	    h.put("Şablon:yao", "yao");
	    h.put("Şablon:yap", "yap");
	    h.put("Şablon:za", "za");
	    h.put("Şablon:zap", "zap");
	    h.put("Şablon:zbl", "zbl");
	    h.put("Şablon:zen", "zen");
	    h.put("Şablon:zun", "zun");
	    h.put("Şablon:zxx", "zxx");
	    h.put("Sami (Kuzey)", "se");
	    h.put("Samice", "smn");
	    h.put("Samoaca", "sm");
	    h.put("Sango dili", "sg");
	    h.put("Sanskritçe", "sa");
	    h.put("Sarduca", "sc");
	    h.put("Savahili dili", "sw");
	    h.put("Sesotho", "st");
	    h.put("Setswana", "tn");
	    h.put("Sicilyaca", "scn");
	    h.put("Siçuan Yi dili", "ii");
	    h.put("Sindi", "sd");
	    h.put("Singalezce", "si");
	    h.put("Sırp-Hırvatça", "sh");
	    h.put("Sırpça", "sr");
	    h.put("Slovakça", "sk");
	    h.put("Slovence", "sl");
	    h.put("Somalice", "so");
	    h.put("Şona", "sn");
	    h.put("Sorbça (Aşağı)", "dsb");
	    h.put("Sorbça (Yukarı)", "hsb");
	    h.put("Sümerce", "sux");
	    h.put("Sundanezce", "su");
	    h.put("Süryanice", "syr");
	    h.put("Svati", "ss");
	    h.put("Tacikçe", "tg");
	    h.put("Tagalogca", "tl");
	    h.put("Tahitice", "ty");
	    h.put("Tamilce", "ta");
	    h.put("Tatarca", "tt");
	    h.put("Tayca", "th");
	    h.put("Telugu", "te");
	    h.put("Tetum", "tet");
	    h.put("Tibetçe", "bo");
	    h.put("Tigrinya", "ti");
	    h.put("Tok Pisin", "tpi");
	    h.put("Tongaca", "to");
	    h.put("Tsonga", "ts");
	    h.put("Tumbukaca", "tum");
	    h.put("Türkçe", "tr");
	    h.put("Türkmence", "tk");
	    h.put("Tuvaca", "tyv");
	    h.put("Tuvalu", "tvl");
	    h.put("Tvi", "tw");
	    h.put("Udmurtça", "udm");
	    h.put("Ukraynaca", "uk");
	    h.put("Urduca", "ur");
	    h.put("Uygurca", "ug");
	    h.put("Valonca", "wa");
	    h.put("Varayca", "war");
	    h.put("Vendaca", "ve");
	    h.put("Vietnamca", "vi");
	    h.put("Volapük", "vo");
	    h.put("Votça", "vot");
	    h.put("Wolof", "wo");
	    h.put("Xhosan", "xh");
	    h.put("Yahudi Almancası", "yi");
	    h.put("Yahudi İspanyolcası", "lad");
	    h.put("Yakutça", "sah");
	    h.put("Yeni Norveççe", "nn");
	    h.put("Yorubaca", "yo");
	    h.put("Yunanca", "el");
	    h.put("Zazaca", "zza");
	    h.put("Zulu", "zu");
	}

	public static String threeLettersCode(String s) {
		return threeLettersCode(h, s);
	}
}
