/**
 * 
 */
package org.getalp.dbnary.lat;

import org.getalp.dbnary.LangTools;

import java.util.HashMap;

/**
 * @author Mariam
 *
 */
public class LatinLangtoCode extends LangTools {
	static HashMap<String,String> h = new HashMap<String,String>();
	// TODO: check if this is usefull and add Latin language names if necessary
	static{
		h.put("abkhaze","ab");
		h.put("achinais","ace");
		h.put("acoli","ach");
		h.put("adangmé","ada");
		h.put("adyghé","ady");
		h.put("afar","aa");
		h.put("afrihili","afh");
		h.put("afrikaans","af");
		h.put("aïnou (Japon)","ain");
		h.put("akan","ak");
		h.put("akkadien","akk");
		h.put("albanais","sq");
		h.put("alémanique","gsw");
		h.put("aléoute","ale");
		h.put("allemand","de");
		h.put("altaï du Sud","alt");
		h.put("amharique","am");
		h.put("ancien français","fro");
		h.put("ancien occitan","pro");
		h.put("angika","anp");
		h.put("anglais","en");
		h.put("anglo-saxon","ang");
		h.put("arabe","ar");
		h.put("aragonais","an");
		h.put("araméen","arc");
		h.put("araméen samaritain","sam");
		h.put("arapaho","arp");
		h.put("arawak","arw");
		h.put("arménien","hy");
		h.put("aroumain","rup");
		h.put("assamais","as");
		h.put("asturien","ast");
		h.put("avar","av");
		h.put("avestique","ae");
		h.put("awadhi","awa");
		h.put("aymara","ay");
		h.put("azéri","az");
		h.put("bachkir","ba");
		h.put("balinais","ban");
		h.put("baloutche","bal");
		h.put("bambara","bm");
		h.put("bas allemand","nds");
		h.put("bas saxon de Frise orientale","frs");
		h.put("basque","eu");
		h.put("bassa (Cameroun)","bas");
		h.put("bas-sorabe","dsb");
		h.put("bedja","bej");
		h.put("bemba","bem");
		h.put("bengali","bn");
		h.put("bhojpuri","bho");
		h.put("bichlamar","bi");
		h.put("biélorusse","be");
		h.put("bikol","bik");
		h.put("bilen","byn");
		h.put("birman","my");
		h.put("bliss","zbl");
		h.put("bosniaque","bs");
		h.put("bouriate","bua");
		h.put("braj","bra");
		h.put("breton","br");
		h.put("bugis","bug");
		h.put("bulgare","bg");
		h.put("caddo","cad");
		h.put("carélien","krl");
		h.put("catalan","ca");
		h.put("cébouano","ceb");
		h.put("chamorro","ch");
		h.put("cherokee","chr");
		h.put("cheyenne","chy");
		h.put("chinois","zh");
		h.put("chipewyan","chp");
		h.put("choctaw","cho");
		h.put("chuukais","chk");
		h.put("cingalais","si");
		h.put("copte","cop");
		h.put("coréen","ko");
		h.put("cornique","kw");
		h.put("corse","co");
		h.put("cri","cr");
		h.put("croate","hr");
		h.put("dakota","dak");
		h.put("danois","da");
		h.put("dargwa","dar");
		h.put("dinka","din");
		h.put("dioula","dyu");
		h.put("divehi","dv");
		h.put("dogri","doi");
		h.put("douala","dua");
		h.put("dzongkha","dz");
		h.put("édo","bin");
		h.put("éfik","efi");
		h.put("égyptien ancien","egy");
		h.put("ékadjouk","eka");
		h.put("élamite","elx");
		h.put("erza","myv");
		h.put("esclave","den");
		h.put("espagnol","es");
		h.put("espéranto","eo");
		h.put("estonien","et");
		h.put("éwé","ee");
		h.put("éwondo","ewo");
		h.put("fang","fan");
		h.put("fanti","fat");
		h.put("féroïen","fo");
		h.put("fidjien","fj");
		h.put("filipino","fil");
		h.put("finnois","fi");
		h.put("flanc-de-chien","dgr");
		h.put("fon","fon");
		h.put("français","fr");
		h.put("frioulan","fur");
		h.put("frison","fy");
		h.put("frison septentrional","frr");
		h.put("ga","gaa");
		h.put("gaélique écossais","gd");
		h.put("gaélique irlandais","ga");
		h.put("galicien","gl");
		h.put("gallois","cy");
		h.put("ganda","lg");
		h.put("gayo","gay");
		h.put("gbaya","gba");
		h.put("géorgien","ka");
		h.put("gilbertin","gil");
		h.put("gond","gon");
		h.put("gorontalo","gor");
		h.put("gotique","got");
		h.put("goudjarati","gu");
		h.put("grébo","grb");
		h.put("grec","el");
		h.put("grec ancien","grc");
		h.put("guarani","gn");
		h.put("guèze","gez");
		h.put("gwich’in","gwi");
		h.put("haïda","hai");
		h.put("haïtien","ht");
		h.put("haoussa","ha");
		h.put("haut-sorabe","hsb");
		h.put("hawaïen","haw");
		h.put("hébreu","he");
		h.put("héréro","hz");
		h.put("hiligaynon","hil");
		h.put("hindi","hi");
		h.put("hiri motou","ho");
		h.put("hittite","hit");
		h.put("hmong","hmn");
		h.put("hongrois","hu");
		h.put("hupa","hup");
		h.put("iakoute","sah");
		h.put("iban","iba");
		h.put("ido","io");
		h.put("igbo","ig");
		h.put("ilocano","ilo");
		h.put("indonésien","id");
		h.put("ingouche","inh");
		h.put("interlingua","ia");
		h.put("interlingue","ie");
		h.put("inuktitut","iu");
		h.put("inupiaq","ik");
		h.put("islandais","is");
		h.put("italien","it");
		h.put("japonais","ja");
		h.put("jargon chinook","chn");
		h.put("javanais","jv");
		h.put("judéo-arabe","jrb");
		h.put("judéo-espagnol","lad");
		h.put("judéo-persan","jpr");
		h.put("kabarde","kbd");
		h.put("kabyle","kab");
		h.put("kachin","kac");
		h.put("kachoube","csb");
		h.put("kalaallisut","kl");
		h.put("kali’na","car");
		h.put("kalmouk","xal");
		h.put("kamba","kam");
		h.put("kannara","kn");
		h.put("kanouri","kr");
		h.put("kapampangan","pam");
		h.put("karakalpak","kaa");
		h.put("karatchaï balkar","krc");
		h.put("kashmiri","ks");
		h.put("kawi","kaw");
		h.put("kazakh","kk");
		h.put("khasi","kha");
		h.put("khmer","km");
		h.put("khotanais","kho");
		h.put("kikongo","kg");
		h.put("kikuyu","ki");
		h.put("kimboundou","kmb");
		h.put("kinyarwanda","rw");
		h.put("kirghiz","ky");
		h.put("kirundi","rn");
		h.put("klingon","tlh");
		h.put("komi","kv");
		h.put("konkânî","kok");
		h.put("kosraéen","kos");
		h.put("koumyk","kum");
		h.put("kpellé","kpe");
		h.put("kuanyama","kj");
		h.put("kurde","ku");
		h.put("kurukh","kru");
		h.put("kutenai","kut");
		h.put("lahnda","lah");
		h.put("lamba","lam");
		h.put("laotien","lo");
		h.put("latin","la");
		h.put("lenape","del");
		h.put("letton","lv");
		h.put("lezghien","lez");
		h.put("limbourgeois","li");
		h.put("lingala","ln");
		h.put("lituanien","lt");
		h.put("lojban","jbo");
		h.put("lomongo","lol");
		h.put("louba-katanga","lu");
		h.put("lounda","lun");
		h.put("lozi","loz");
		h.put("luba-lulua","lua");
		h.put("luiseño","lui");
		h.put("luo (Kenya, Tanzanie)","luo");
		h.put("luxembourgeois","lb");
		h.put("macédonien","mk");
		h.put("madourais","mad");
		h.put("magahi","mag");
		h.put("maithili","mai");
		h.put("makassar","mak");
		h.put("malais","ms");
		h.put("malayalam","ml");
		h.put("malgache","mg");
		h.put("maltais","mt");
		h.put("mandar","mdr");
		h.put("mandchou","mnc");
		h.put("mandingue","man");
		h.put("manipourî","mni");
		h.put("mannois","gv");
		h.put("maori","mi");
		h.put("mapuche","arn");
		h.put("marathe","mr");
		h.put("mari","chm");
		h.put("marshallais","mh");
		h.put("marvari","mwr");
		h.put("massaï","mas");
		h.put("mendé","men");
		h.put("micmac","mic");
		h.put("minangkabau","min");
		h.put("mirandais","mwl");
		h.put("mizo","lus");
		h.put("mohawk","moh");
		h.put("mokcha","mdf");
		h.put("moldave","mo");
		h.put("mongol","mn");
		h.put("moré","mos");
		h.put("moyen anglais","enm");
		h.put("moyen français","frm");
		h.put("moyen haut-allemand","gmh");
		h.put("moyen irlandais","mga");
		h.put("moyen néerlandais","dum");
		h.put("muisca","chb");
		h.put("muskogee","mus");
		h.put("n’ko","nqo");
		h.put("napolitain","nap");
		h.put("nauruan","na");
		h.put("navajo","nv");
		h.put("ndébélé du Nord","nd");
		h.put("ndébélé du Sud","nr");
		h.put("ndonga","ng");
		h.put("néerlandais","nl");
		h.put("népalais","ne");
		h.put("newari","new");
		h.put("newari classique","nwc");
		h.put("nias","nia");
		h.put("niuéen","niu");
		h.put("nogaï","nog");
		h.put("norvégien","no");
		h.put("norvégien (bokmål)","nb");
		h.put("norvégien (nynorsk)","nn");
		h.put("nyamwezi","nym");
		h.put("nyanja","ny");
		h.put("nyankolé","nyn");
		h.put("nyoro","nyo");
		h.put("nzéma","nzi");
		h.put("occitan","oc");
		h.put("ojibwa","oj");
		h.put("oriya","or");
		h.put("oromo","om");
		h.put("osage","osa");
		h.put("ossète","os");
		h.put("oudmourte","udm");
		h.put("ougaritique","uga");
		h.put("ouïghour","ug");
		h.put("oumboundou","umb");
		h.put("ourdou","ur");
		h.put("ouzbek","uz");
		h.put("pachto","ps");
		h.put("palau","pau");
		h.put("pali","pi");
		h.put("pangasinan","pag");
		h.put("papiamento","pap");
		h.put("pehlevi","pal");
		h.put("pendjabi","pa");
		h.put("persan","fa");
		h.put("peul","ff");
		h.put("phénicien","phn");
		h.put("pied-noir","bla");
		h.put("pohnpei","pon");
		h.put("polonais","pl");
		h.put("portugais","pt");
		h.put("quechua","qu");
		h.put("rajasthani","raj");
		h.put("rapanui","rap");
		h.put("rarotongien","rar");
		h.put("romanche","rm");
		h.put("romani","rom");
		h.put("roumain","ro");
		h.put("russe","ru");
		h.put("same d’Inari","smn");
		h.put("same de Lule","smj");
		h.put("same du Nord","se");
		h.put("same du Sud","sma");
		h.put("same skolt","sms");
		h.put("samoan","sm");
		h.put("sandawé","sad");
		h.put("sango","sg");
		h.put("sans contenu linguistique","zxx");
		h.put("sanskrit","sa");
		h.put("santal","sat");
		h.put("sarde","sc");
		h.put("sassak","sas");
		h.put("scots","sco");
		h.put("selkoupe","sel");
		h.put("serbe","sr");
		h.put("serbo-croate","sh");
		h.put("sérère","srr");
		h.put("shan","shn");
		h.put("shona","sn");
		h.put("sicilien","scn");
		h.put("sidamo","sid");
		h.put("sindhi","sd");
		h.put("slovaque","sk");
		h.put("slovène","sl");
		h.put("sogdien","sog");
		h.put("somali","so");
		h.put("soninké","snk");
		h.put("sotho du Nord","nso");
		h.put("sotho du Sud","st");
		h.put("soukouma","suk");
		h.put("soundanais","su");
		h.put("soussou","sus");
		h.put("sranan","srn");
		h.put("suédois","sv");
		h.put("sumérien","sux");
		h.put("swahili","sw");
		h.put("swazi","ss");
		h.put("syriaque","syr");
		h.put("syriaque classique","syc");
		h.put("tadjik","tg");
		h.put("tagalog","tl");
		h.put("tahitien","ty");
		h.put("tamasheq (macrolangue)","tmh");
		h.put("tamoul","ta");
		h.put("tatar de Crimée","crh");
		h.put("tatare","tt");
		h.put("tchaghataï","chg");
		h.put("tchèque","cs");
		h.put("tchétchène","ce");
		h.put("tchouvache","cv");
		h.put("télougou","te");
		h.put("temné","tem");
		h.put("téréno","ter");
		h.put("tétoum","tet");
		h.put("thaï","th");
		h.put("tibétain","bo");
		h.put("tigré","tig");
		h.put("tigrigna","ti");
		h.put("tiv","tiv");
		h.put("tlingit","tli");
		h.put("tok pisin","tpi");
		h.put("tokelauien","tkl");
		h.put("tonga","tog");
		h.put("tongien","to");
		h.put("touvain","tyv");
		h.put("tsimshian","tsi");
		h.put("tsonga","ts");
		h.put("tswana","tn");
		h.put("tumbuka","tum");
		h.put("turc","tr");
		h.put("turc ottoman","ota");
		h.put("turkmène","tk");
		h.put("tuvalu","tvl");
		h.put("twi","tw");
		h.put("ukrainien","uk");
		h.put("vaï","vai");
		h.put("venda","ve");
		h.put("vieil irlandais","sga");
		h.put("vietnamien","vi");
		h.put("vieux haut allemand","goh");
		h.put("vieux norrois","non");
		h.put("vieux slave","cu");
		h.put("vieux-perse","peo");
		h.put("volapük","vo");
		h.put("vote","vot");
		h.put("wallon","wa");
		h.put("waray","war");
		h.put("washo","was");
		h.put("wolaytta","wal");
		h.put("wolof","wo");
		h.put("xhosa","xh");
		h.put("yao","yao");
		h.put("yapois","yap");
		h.put("yi","ii");
		h.put("yiddish","yi");
		h.put("yoruba","yo");
		h.put("zapotèque","zap");
		h.put("zazaki","zza");
		h.put("zénaga","zen");
		h.put("zhuang","za");
		h.put("zoulou","zu");
		h.put("zuni","zun");
	}

	public static String threeLettersCode(String s) {
		return threeLettersCode(h, s);
	}
}
