package org.getalp.dbnary.mlg;

import org.getalp.dbnary.LangTools;

import java.util.HashMap;

/**
 * @author Roques
 *
 */
public class MalagasyLangToCode extends LangTools {
	static HashMap<String,String> h = new HashMap<>();
	static {
		h.put("abkhaz", "ab");
		h.put("acehnese", "ace");
		h.put("acholi", "ach");
		h.put("adangme", "ada");
		h.put("adyghe", "ady");
		h.put("lavitra", "aa");
		h.put("abkaza", "aar");
		h.put("afara", "aar");
		h.put("afrihili", "afh");
		h.put("afrikaans", "af");
		h.put("ainu", "ain");
		h.put("akan", "ak");
		h.put("akadianina", "akk");
		h.put("albaney", "sq");
		h.put("alemannic alemaina", "gsw");
		h.put("aleut", "ale");
		h.put("amharic", "am");
		h.put("teny", "grc");
		h.put("angika", "anp");
		h.put("arabo", "ar");
		h.put("aragonese", "an");
		h.put("teny aramianina", "arc");
		h.put("arapaho", "arp");
		h.put("arawak", "arw");
		h.put("armeniana", "hy");
		h.put("aromainina", "rup");
		h.put("assamese", "as");
		h.put("anarana", "ast");
		h.put("avar", "av");
		h.put("avestan", "ae");
		h.put("awadhi", "awa");
		h.put("aymara", "ay");
		h.put("azeri", "az");
		h.put("balinese", "ban");
		h.put("baluchi", "bal");
		h.put("bambara", "bm");
		h.put("basaa", "bas");
		h.put("bashkir", "ba");
		h.put("eoskara", "eu");
		h.put("beja", "bej");
		h.put("belarosy", "be");
		h.put("bemba", "bem");
		h.put("bengali", "bn");
		h.put("bhojpuri", "bho");
		h.put("bikol", "bik");
		h.put("bini", "bin");
		h.put("bislama", "bi");
		h.put("blackfoot", "bla");
		h.put("blin", "byn");
		h.put("bosniaka", "bs");
		h.put("bôsniaka", "bs");
		h.put("braj", "bra");
		h.put("bretôna", "br");
		h.put("buginese", "bug");
		h.put("biolgara", "bg");
		h.put("boromesa", "my");
		h.put("buryat", "bua");
		h.put("caddo", "cad");
		h.put("katalana", "ca");
		h.put("cebuano", "ceb");
		h.put("chagatai", "chg");
		h.put("chamorro", "ch");
		h.put("chechen", "ce");
		h.put("cherokee", "chr");
		h.put("cheyenne", "chy");
		h.put("chibcha", "chb");
		h.put("chichewa", "ny");
		h.put("chinook teknika,", "chn");
		h.put("chipewyan", "chp");
		h.put("choctaw", "cho");
		h.put("chuuk", "chk");
		h.put("chuvash", "cv");
		h.put("classical newari", "nwc");
		h.put("classical syriac", "syc");
		h.put("coptic", "cop");
		h.put("cornish", "kw");
		h.put("kôrsa", "co");
		h.put("cree", "cr");
		h.put("creek", "mus");
		h.put("crimean tatar", "crh");
		h.put("krôasiana", "hr");
		h.put("tseka", "cs");
		h.put("dakota", "dak");
		h.put("danesy", "da");
		h.put("danisy", "da");
		h.put("dargwa", "dar");
		h.put("dhivehi", "dv");
		h.put("divehi", "dv");
		h.put("dinka", "din");
		h.put("dogri", "doi");
		h.put("dogrib", "dgr");
		h.put("antananarivu", "dua");
		h.put("nerlandey", "nl");
		h.put("dyula", "dyu");
		h.put("dzongkha", "dz");
		h.put("eastern frisian", "frs");
		h.put("efik", "efi");
		h.put("egyptian", "egy");
		h.put("ekajuk", "eka");
		h.put("elama", "elx");
		h.put("anglisy", "en");
		h.put("erzya", "myv");
		h.put("esperanto", "eo");
		h.put("estôniana", "et");
		h.put("estoniana", "et");
		h.put("ewe", "ee");
		h.put("ewondo", "ewo");
		h.put("fanti", "fat");
		h.put("feroianina", "fo");
		h.put("fijian", "fj");
		h.put("finoa", "fi");
		h.put("fon", "fon");
		h.put("frantsay", "fr");
		h.put("friulian", "fur");
		h.put("fula", "ff");
		h.put("ga", "gaa");
		h.put("galibi karaiba", "car");
		h.put("galisiana", "gl");
		h.put("gayo", "gay");
		h.put("gbaya", "gba");
		h.put("ge'ez", "gez");
		h.put("jeôrjiana", "ka");
		h.put("alemaina", "de");
		h.put("gilbert", "gil");
		h.put("gondi", "gon");
		h.put("gorontalo", "gor");
		h.put("gothic", "got");
		h.put("grebo", "grb");
		h.put("grika", "el");
		h.put("grika taloha", "el");
		h.put("greenlandic", "kl");
		h.put("guaraní", "gn");
		h.put("goarani", "gn");
		h.put("gojaraty", "gu");
		h.put("gwich'in", "gwi");
		h.put("haida", "hai");
		h.put("haitiana creole", "ht");
		h.put("haisianina", "ht");
		h.put("haosa", "ha");
		h.put("hawaii", "haw");
		h.put("ebreo", "he");
		h.put("ebreo taloha", "he");
		h.put("herero", "hz");
		h.put("hiligaynon", "hil");
		h.put("hindi", "hi");
		h.put("hiri motu", "ho");
		h.put("hetita", "hit");
		h.put("hmong", "hmn");
		h.put("hongariana", "hu");
		h.put("hupa", "hup");
		h.put("iban", "iba");
		h.put("islandey", "is");
		h.put("limborgisy", "is");
		h.put("ido", "io");
		h.put("igbo", "ig");
		h.put("ilocano", "ilo");
		h.put("inari sami", "smn");
		h.put("indonezianina", "id");
		h.put("ingush", "inh");
		h.put("inoktitoty", "ia");
		h.put("interlingua", "ia");
		h.put("interlingue", "ie");
		h.put("inuktitut", "iu");
		h.put("iñupiak", "ik");
		h.put("irlandey", "ga");
		h.put("italiana", "it");
		h.put("italianina", "it");
		h.put("japoney", "ja");
		h.put("javaney", "jv");
		h.put("jingpho", "kac");
		h.put("judeo-teny arabo", "jrb");
		h.put("judeo-persianina", "jpr");
		h.put("kabardian", "kbd");
		h.put("kabyle", "kab");
		h.put("kalmyk", "xal");
		h.put("kamba", "kam");
		h.put("kannada", "kn");
		h.put("kannara", "kr");
		h.put("kapampangan", "pam");
		h.put("karachay-balkar", "krc");
		h.put("karakalpak", "kaa");
		h.put("karelian", "krl");
		h.put("kashmiri", "ks");
		h.put("kashubian", "csb");
		h.put("kazakh", "kk");
		h.put("kazàka", "kk");
		h.put("khasi", "kha");
		h.put("kimera", "km");
		h.put("khotanese", "kho");
		h.put("kikuyu", "ki");
		h.put("kimbundu", "kmb");
		h.put("kinyarwanda", "rw");
		h.put("kirundi", "rn");
		h.put("komi-zyrian", "kv");
		h.put("kongo", "kg");
		h.put("konkani", "kok");
		h.put("koreana", "ko");
		h.put("korana", "ko");
		h.put("kosrae", "kos");
		h.put("kpelle", "kpe");
		h.put("kumyk", "kum");
		h.put("kiorda", "ku");
		h.put("kurukh", "kru");
		h.put("kutenai", "kut");
		h.put("kwanyama", "kj");
		h.put("kyrgyz", "ky");
		h.put("ladino", "lad");
		h.put("lahnda", "lah");
		h.put("lamba", "lam");
		h.put("laôsiana", "lo");
		h.put("latina", "la");
		h.put("letôna", "lv");
		h.put("lenape", "del");
		h.put("lezgi", "lez");
		h.put("limburgish", "li");
		h.put("lingala", "ln");
		h.put("litoanianina", "lt");
		h.put("lojban", "jbo");
		h.put("low german", "nds");
		h.put("lower sorbian", "dsb");
		h.put("lozi", "loz");
		h.put("luba-katanga", "lu");
		h.put("luganda", "lg");
		h.put("luiseno", "lui");
		h.put("lule sami", "smj");
		h.put("lunda", "lun");
		h.put("luo", "luo");
		h.put("luxembourgish", "lb");
		h.put("maasai", "mas");
		h.put("masedôniana", "mk");
		h.put("masedônianina", "mk");
		h.put("madurese", "mad");
		h.put("magahi", "mag");
		h.put("maithili", "mai");
		h.put("mailthili", "mai");
		h.put("makasar", "mak");
		h.put("malagasy", "mg");
		h.put("malay", "ms");
		h.put("malayalam", "ml");
		h.put("maltey", "mt");
		h.put("manchu", "mnc");
		h.put("mandar", "mdr");
		h.put("sinoa", "zh");
		h.put("fijianina", "zh");
		h.put("sinoa mandarina", "cmn");
		h.put("kantoney", "yue");
		h.put("mandingo", "man");
		h.put("manipuri", "mni");
		h.put("manx", "gv");
		h.put("maori", "mi");
		h.put("mapudungun", "arn");
		h.put("marathi", "mr");
		h.put("mari", "chm");
		h.put("marshall", "mh");
		h.put("marwari", "mwr");
		h.put("mende", "men");
		h.put("afovoany anarana iombonana", "dum");
		h.put("middle anglisy", "enm");
		h.put("afovoany french", "frm");
		h.put("middle high alemaina", "gmh");
		h.put("middle irlandey", "mga");
		h.put("middle persana", "pal");
		h.put("mi'kmaq", "mic");
		h.put("minangkabau", "min");
		h.put("mirandese", "mwl");
		h.put("mizo", "lus");
		h.put("mohawk", "moh");
		h.put("moksha", "mdf");
		h.put("mongo", "lol");
		h.put("môngôly", "mn");
		h.put("mongoly", "mn");
		h.put("bebe kokoa", "mos");
		h.put("nahuatl", "nah");
		h.put("ndau", "na");
		h.put("navajo", "nv");
		h.put("ndonga", "ng");
		h.put("neapolitan", "nap");
		h.put("nepali", "ne");
		h.put("nepaley", "ne");
		h.put("newari", "new");
		h.put("nias", "nia");
		h.put("niue", "niu");
		h.put("n'ko", "nqo");
		h.put("nogai", "nog");
		h.put("north frisian", "frr");
		h.put("northern ndebele", "nd");
		h.put("northern sami", "se");
		h.put("northern sotho", "nso");
		h.put("norvejiana", "no");
		h.put("norvejiana (bokmal)", "nb");
		h.put("norvejiana (nynorsk)", "nn");
		h.put("nyamwezi", "nym");
		h.put("nyankole", "nyn");
		h.put("nyoro", "nyo");
		h.put("nzima", "nzi");
		h.put("occitan", "oc");
		h.put("ojibwe", "oj");
		h.put("old church slavonika", "cu");
		h.put("old english", "ang");
		h.put("old french", "fro");
		h.put("old high alemaina", "goh");
		h.put("old irlandey", "sga");
		h.put("old javaney", "kaw");
		h.put("teny anglisy", "non");
		h.put("old provençal", "pro");
		h.put("old persana", "peo");
		h.put("oriya", "or");
		h.put("oromo", "om");
		h.put("osage", "osa");
		h.put("ossetian", "os");
		h.put("ottoman tiorka", "ota");
		h.put("pahouin", "fan");
		h.put("palauan", "pau");
		h.put("pali", "pi");
		h.put("pangasinan", "pag");
		h.put("papiamento", "pap");
		h.put("pasitoa", "ps");
		h.put("persana", "fa");
		h.put("fenisianina", "phn");
		h.put("pohnpeian", "pon");
		h.put("poloney", "pl");
		h.put("portogey", "pt");
		h.put("punjabi", "pa");
		h.put("panjabi", "pa");
		h.put("kitsoà", "qu");
		h.put("rajasthani", "raj");
		h.put("rapa nui", "rap");
		h.put("rarotonga", "rar");
		h.put("romainina", "rom");
		h.put("romantsa", "ro");
		h.put("meny", "rm");
		h.put("rosy", "ru");
		h.put("samaritanina aramaic", "sam");
		h.put("samoanina", "sm");
		h.put("sandawe", "sad");
		h.put("sango", "sg");
		h.put("sanskrity", "sa");
		h.put("santali", "sat");
		h.put("sardinian", "sc");
		h.put("sasak", "sas");
		h.put("scots", "sco");
		h.put("gaelika", "gd");
		h.put("selkup", "sel");
		h.put("serba", "sr");
		h.put("serba krôata", "sh");
		h.put("serer", "srr");
		h.put("shan", "shn");
		h.put("shona", "sn");
		h.put("sichuan yi", "ii");
		h.put("sicilian", "scn");
		h.put("sidamo", "sid");
		h.put("sindhi", "sd");
		h.put("sinhalese", "si");
		h.put("siska", "tog");
		h.put("skolt sami", "sms");
		h.put("slavey", "den");
		h.put("silaovaka", "sk");
		h.put("silaovena", "sl");
		h.put("singalesa", "sin");
		h.put("sogdian", "sog");
		h.put("somali", "so");
		h.put("songay", "ses");
		h.put("soninke", "snk");
		h.put("sotho", "st");
		h.put("southern altai", "alt");
		h.put("southern ndebele", "nr");
		h.put("southern sami", "sma");
		h.put("espaniôla", "es");
		h.put("espaniola", "es");
		h.put("sranan tongo", "srn");
		h.put("sukuma", "suk");
		h.put("somerianina", "sux");
		h.put("sundanese", "su");
		h.put("susu", "sus");
		h.put("soahily", "sw");
		h.put("swati", "ss");
		h.put("soedoa", "sv");
		h.put("syriac", "syr");
		h.put("tagalaoga", "tl");
		h.put("tahisianina", "ty");
		h.put("tajik", "tg");
		h.put("tamashek", "tmh");
		h.put("tamily", "ta");
		h.put("tatar", "tt");
		h.put("telogo", "te");
		h.put("endrika: fil", "fil");
		h.put("endrika: mis", "mis");
		h.put("endrika: mo", "mo");
		h.put("endrika: tlh", "tlh");
		h.put("endrika: zbl", "zbl");
		h.put("endrika: zxx", "zxx");
		h.put("tereno", "ter");
		h.put("tetum", "tet");
		h.put("tailandey", "th");
		h.put("tibetana", "bo");
		h.put("tigre", "tig");
		h.put("tigrinya", "ti");
		h.put("timne", "tem");
		h.put("tivi", "tiv");
		h.put("tlingit", "tli");
		h.put("tok pisin", "tpi");
		h.put("tokelauan", "tkl");
		h.put("tongan", "to");
		h.put("translingual", "mul");
		h.put("tshiluba", "lua");
		h.put("tsimshian", "tsi");
		h.put("tsonga", "ts");
		h.put("tswana", "tn");
		h.put("tumbuka", "tum");
		h.put("tiorka", "tr");
		h.put("turkmen", "tk");
		h.put("tuvalu", "tvl");
		h.put("tuvan", "tyv");
		h.put("twi", "tw");
		h.put("udmurt", "udm");
		h.put("ougarit", "uga");
		h.put("okrainianina", "uk");
		h.put("umbundu", "umb");
		h.put("undetermined", "und");
		h.put("upper sorbian", "hsb");
		h.put("urdu", "ur");
		h.put("uyghur", "ug");
		h.put("ozbeka", "uz");
		h.put("vai", "vai");
		h.put("venda", "ve");
		h.put("vietnamiana", "vi");
		h.put("volapoky", "vo");
		h.put("votic", "vot");
		h.put("walamo", "wal");
		h.put("valôna", "wa");
		h.put("waray-waray", "war");
		h.put("washo", "was");
		h.put("welsh", "cy");
		h.put("west frisian", "fy");
		h.put("wolof", "wo");
		h.put("xhosa", "xh");
		h.put("yakut", "sah");
		h.put("yao", "yao");
		h.put("yapese", "yap");
		h.put("yidisy", "yi");
		h.put("yoruba", "yo");
		h.put("yoroba", "yo");
		h.put("zapotec", "zap");
		h.put("zazaki", "zza");
		h.put("zenaga", "zen");
		h.put("zhuang", "za");
		h.put("zulu", "zu");
		h.put("zuni", "zun");
	}
	
	public static String threeLettersCode(String s) {
		return threeLettersCode(h, s);
	}
}
