package org.getalp.blexisma.cougaarcom;

import java.io.Serializable;
import java.util.ArrayList;

import org.cougaar.core.util.UID;

/**
 * @author Alexandre Labadié
 * */
public class ProxRequest implements Serializable {

	/**
	 * Autogenerated serial version UID
	 */
	private static final long serialVersionUID = -7714657320628421056L;
	private final UID uid;
	private final String lemme;
	private final String lang;
	private final String regex;
	private final int size;
	private ArrayList<String> proxList;
	private boolean end;
	
	public ProxRequest(String lemme, String lang, UID uid) {
		this.lemme = lemme;
		this.uid = uid;
		this.lang = lang;
		this.regex = null;
		this.size = 10;
		proxList = new ArrayList<String>();
		end = false;
	}

	public ProxRequest(String lemme, String lang, String regex, int size, UID uid) {
		this.lemme = lemme;
		this.uid = uid;
		this.lang = lang;
		this.regex = regex;
		this.size = size;
		proxList = new ArrayList<String>();
		end = false;
	}
	
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public UID getUid() {
		return uid;
	}

	public String getLemme() {
		return lemme;
	}

	public boolean isEnd() {
		return end;
	}

	public void setEnd(boolean end) {
		this.end = end;
	}

	public ArrayList<String> getProxList() {
		return proxList;
	}

	public void setProxList(ArrayList<String> proxList) {
		this.proxList = proxList;
	}

	public String getLang() {
		return lang;
	}

	/**
	 * @return the regex
	 */
	public String getRegex() {
		return regex;
	}

	/**
	 * @return the size
	 */
	public int getSize() {
		return size;
	}
	
}
